- lib/tasks/populate.rake
- Populate databases as it should be done with active_record
> Remove populate join table hack

- app/models/group.rb
- app/models/person.rb
- app/models/space.rb
- spec/controllers/groups_controller_spec.rb
- spec/controllers/persons_controller_spec.rb
- spec/factories/groups.rb
- spec/factories/persons.rb
- spec/factories/spaces.rb
- spec/models/group_spec.rb
- spec/models/person_spec.rb
- spec/models/space_spec.rb
- spec/views/groups/show.html.erb_spec.rb
- spec/views/persons/show.html.erb_spec.rb
Updates validators and specs.
Rework factories. Seems to be easier if we create the related items in the spec instead of in the factories. We can revisit this later.
> Validator with has_many :through

- app/dashboards/building_dashboard.rb
- app/models/building.rb
- app/views/buildings/_building.json.jbuilder
- app/views/buildings/show.html.erb
- db/data.yml
- db/migrate/20180807201302_delete_accessibility_from_building.rb
- db/schema.rb
- lib/tasks/populate.rake
- spec/factories/buildings.rb
- spec/models/building_spec.rb
Issue #LWR-132 - Accessibility details can be included in the description. It doesn’t need a separate field.
> Remove accessibility from building class

- app/dashboards/space_dashboard.rb
- app/models/space.rb
- app/views/spaces/show.html.erb
- db/data.yml
- db/migrate/20180807201302_delete_accessibility_from_building.rb
- db/migrate/20180807201302_remove_accessibility_from_building.rb
- db/migrate/20180807203011_remove_location_from_space.rb
- db/schema.rb
- lib/tasks/populate.rake
- spec/factories/spaces.rb
- spec/models/space_spec.rb
Issue #LWR-134 - This is a duplicate to “description” and “related building”
> Remove location from space

- app/dashboards/building_dashboard.rb
- app/dashboards/space_dashboard.rb
- app/fields/description_field.rb
- app/fields/required_belongs_to_field.rb
- app/fields/required_string_field.rb
- app/fields/required_text_field.rb
- app/models/building.rb
- app/models/space.rb
- app/views/fields/description_field/_form.html.erb
- app/views/fields/description_field/_index.html.erb
- app/views/fields/description_field/_show.html.erb
- app/views/fields/required_belongs_to_field/_form.html.erb
- app/views/fields/required_belongs_to_field/_index.html.erb
- app/views/fields/required_belongs_to_field/_show.html.erb
- app/views/fields/required_string_field/_form.html.erb
- app/views/fields/required_string_field/_index.html.erb
- app/views/fields/required_string_field/_show.html.erb
- app/views/fields/required_text_field/_form.html.erb
- app/views/fields/required_text_field/_index.html.erb
- app/views/fields/required_text_field/_show.html.erb
Issue #LWR-133 - Update Space fields and required/not required settings
- Does not address building map. Do this in a separate branch
> Mark required fields for spaces

- app/dashboards/building_dashboard.rb
- app/fields/phone_field.rb
- app/fields/required_phone_field.rb
- app/models/building.rb
- app/models/concerns/input_cleaner.rb
- app/views/fields/phone_field/_form.html.erb
- app/views/fields/phone_field/_index.html.erb
- app/views/fields/phone_field/_show.html.erb
- app/views/fields/required_phone_field/_form.html.erb
- app/views/fields/required_phone_field/_index.html.erb
- app/views/fields/required_phone_field/_show.html.erb
Issue #LWR-128
- Allows for phone format with hyphens
- Normalizes phone number to proper format
- Displays phone as hypenated numbers
> Add phone number aid

- app/dashboards/person_dashboard.rb
Issue #LWR-135
- NOTE: Cannot get hasmany fields customized to show as required.
> Denote required fields

- app/dashboards/person_dashboard.rb
- app/fields/required_has_many_field.rb
- app/views/fields/required_has_many_field/_form.html.erb
- app/views/fields/required_has_many_field/_index.html.erb
- app/views/fields/required_has_many_field/_show.html.erb
Issue #LWR-135
- Specify "field-unit--has-many" class selector to use standard 
administrate selectize form field
- Uses v0.9.0 of has_many show field partial. v0.10.0 won't work in this 
version.
> Render Person's group field as a required field

- app/dashboards/group_dashboard.rb
- app/views/persons/show.html.erb
- config/application.rb
Move group select options into config.
> Collections

- Gemfile
- Gemfile.lock
- app/models/building.rb
- app/models/space.rb
- spec/factories/groups.rb
- spec/factories/persons.rb
- spec/factories/spaces.rb
- spec/models/account_spec.rb
- spec/models/building_spec.rb
- spec/models/group_contact_spec.rb
- spec/models/member_spec.rb
- spec/models/occupant_spec.rb
- spec/models/person_spec.rb
- spec/models/space_group_spec.rb
- spec/models/space_spec.rb
- spec/requests/buildings_spec.rb
- spec/requests/groups_spec.rb
- spec/requests/people_spec.rb
- spec/requests/spaces_spec.rb
- Improve specs with mutation testing - Able to cover all models. TBD controller coverage
- Added join model specs.
> Improve and add specs

- .gitignore
- .travis.yml
- Gemfile
- Gemfile.lock
> Setup Travis CI

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_footer.scss
- app/views/application/_footer.html.erb
- app/views/application/_header_navbar.html.erb
- app/views/layouts/application.html.erb
This should restore the scrolling functionality.
> Updates to fix scrolling and page structure issues.

- README.md
- app/views/devise/sessions/new.html.erb
- Enable login page for development
- Disable auto-forward for development
- Instructions to add users for development
> Show a user login page for development

- app/controllers/admin/application_controller.rb
- app/dashboards/person_dashboard.rb
- app/models/building.rb
- app/models/space.rb
- app/views/admin/application/_form.html.erb
- config/initializers/monkey_patches.rb
- spec/models/building_spec.rb
- spec/models/space_spec.rb
Only an admin can upload or modify photos because we have specific constraint requirements on images.
> Only allow entering image for admin accounts.

- app/assets/stylesheets/partials/_header.scss
- app/controllers/admin/alerts_controller.rb
- app/controllers/alerts_controller.rb
- app/controllers/application_controller.rb
- app/dashboards/alert_dashboard.rb
- app/models/ability.rb
- app/models/alert.rb
- app/views/alerts/index.html.erb
- app/views/alerts/show.html.erb
- app/views/application/_header_navbar.html.erb
- app/views/fields/description_field/_index.html.erb
- config/routes.rb
- db/migrate/20180913154916_create_alerts.rb
- db/schema.rb
Published option toggles display.
> Added alerts model, dashboard, and views. 

- db/schema.rb
Otherwise we get git conflicts on attaempted deploys.
> Make sure schema matches migrations

- app/assets/stylesheets/application.scss
- app/views/application/index.html.erb
This mockup is a first iteration, no responsiveness, and will be changed more in future.
> #MAN-26 removed search option and cleaned up css.

- lib/tasks/populate.rake
- Had left over require from when attempting to use FactoryBot to
seed data.
> Remove unused gem from development/production

- app/assets/stylesheets/application.scss
- app/views/application/_header_navbar.html.erb
- app/views/application/index.html.erb
- app/views/buildings/index.html.erb
- app/views/buildings/show.html.erb
- app/views/groups/index.html.erb
- app/views/groups/show.html.erb
- app/views/library_hours/index.html.erb
- app/views/library_hours/show.html.erb
- app/views/persons/index.html.erb
- app/views/persons/show.html.erb
- app/views/services/index.html.erb
- app/views/services/show.html.erb
- app/views/spaces/index.html.erb
- app/views/spaces/show.html.erb
Moved green bar out of header partial and into views since this bar will be used as page title, often pulling from instance variable not available in partials.
> Moved green bar out of header

- app/views/layouts/application.html.erb
They were being cut off on homepage display.
> Moved flash notices out from under search bar to top of page.

- db/migrate/20181025181642_remove_phone_and_email_from_groups.rb
> DOn't drop the columns

- app/controllers/blog_posts_controller.rb
- app/models/blog.rb
- app/models/blog_post.rb
- app/views/blog_posts/index.html.erb
- config/routes.rb
- db/migrate/20181016195052_create_blog_posts.rb
- db/schema.rb
- spec/factories/blog_posts.rb
- spec/factories/persons.rb
- spec/models/blog_post_spec.rb
- spec/models/person_spec.rb
Connects blog posts to individual Blog
Updates the Person fixture to handle its own dependent associations.
> Add model, controller & migration for BlogPosts

- spec/models/account_spec.rb
- spec/models/blog_spec.rb
- spec/models/building_spec.rb
- spec/models/event_spec.rb
- spec/models/group_spec.rb
- spec/models/library_hours_spec.rb
- spec/models/person_spec.rb
- spec/models/service_spec.rb
- spec/models/space_spec.rb
- spec/services/sync_events_spec.rb
> Remove more stray DatabalseCleaner calls

- app/views/application/_footer.html.erb
This prevents errors within the Devise namespace (login page).
> Used model path in links rather than controller based paths.

- app/controllers/admin/events_controller.rb
- app/views/admin/events/_collection.html.erb
- app/views/admin/events/index.html.erb
- config/locales/en.yml
- config/routes.rb
> MAN-40 - Create Admin Button to Start Events Sync

- app/controllers/admin/events_controller.rb
- app/dashboards/event_dashboard.rb
- db/migrate/20181130190236_add_ensemble_id_to_events.rb
- db/schema.rb
- spec/factories/events.rb
- spec/models/event_spec.rb
Create collections administrate
Associate collections and buildings
Administrate collections
Administrate Tests
Created workaround for SortBy bug
Added missing AltText field to edit form
> MAN-78 Link Past Events to Video

- app/controllers/library_hours_controller.rb
- app/views/library_hours/index.html.erb
#MAN-69
Add plus one (+1) to date range for db data. Need to review this in future. 
Adds check for nil data on nav controls date display. Re: HoneyBadger notification: https://app.honeybadger.io/projects/58150/faults/42651534
> Date Range fix for navigating weeks

- app/models/event.rb
- app/views/policies/show.html.erb
- config/brakeman.ignore
- Address Issue #MAN-77
- View was displaying raw html
> Fixes text display

- app/controllers/persons_controller.rb
- app/views/persons/index.html.erb
- spec/requests/people_spec.rb
#MAN-113
Sort the index page by last name, first name, alphabetical
- Sorted instance variable of persons by last_name, first_name. 
- Adjusted view to display last name first. 
- Fixed to tests to expect last_name and not 'name'.
> MAN-113_Persons_index_sort

- app/assets/javascripts/application.js
- app/assets/stylesheets/partials/_header.scss
- app/views/application/_header_navbar.html.erb
#MAN-123 
Please create a responsive site header that includes the logo, site name (Temple University Libraries), the right side navigation, the green bar and the search box.
Please look at the responsive design entity sample attached for Rachel's design.
*********
- Added hamburger icon and hidden main-menu to code
- Added Javascript to handle the click events and toggle the visibility of icon and menu based on bootstrap classes
- Added css to style the hidden/shown hamburger icon and the hidden menu when displayed, and to be hidden when clicked again
> #MAN-123 Responsive Header

- app/models/blog_post.rb
- db/migrate/20181211214242_add_content_hash_to_blog_posts.rb
- db/migrate/20181211214307_change_last_updated_date_to_publication_date_in_blog_posts.rb
- db/schema.rb
- spec/factories/blog_posts.rb
- spec/models/blog_post_spec.rb
- #MAN-146 Adds content_hash field
- #MAN-147 Change list_modification_date to publication_date
> Add content_hash and change last_modified date to publication date

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/events.scss
- app/assets/stylesheets/partials/_card-rows.scss
- app/models/concerns/input_cleaner.rb
- app/models/event.rb
- app/services/sync_service/events.rb
- app/views/events/_visit.html.erb
- app/views/events/show.html.erb
- config/routes.rb
MAN-139
Please apply design to the attached wireframe for events. event template.pdf
> Man-139 event design

- app/assets/stylesheets/application.scss
- app/views/buildings/_visit.html.erb
- app/views/events/_visit.html.erb
- app/views/groups/_show_members.html.erb
- app/views/library_hours/index.html.erb
- app/views/pages/ambler.html.erb
- app/views/pages/home.html.erb
- app/views/pages/hsl.html.erb
- app/views/persons/show.html.erb
- app/views/spaces/_policies.html.erb
- app/views/spaces/_services.html.erb
- app/views/spaces/_visit.html.erb
MAN-131
Please add a maximum width to the center section of the website on all pages when the site expands beyond a certain width as discussed in the core team meeting on 11/30.
*****************************
Add containers to other rows on model pages and mini-pages
Update order of media queries
Add links to homepage first CTArow
> Add containers to homepage rows

- config/application.rb
#MAN-16 Service_category service listed on same row
Move "research data services" to next row.
**********************
Translation: sort entries in drop-down lists
> Ordered select list options alphabetically.

- app/assets/stylesheets/partials/_card-rows.scss
- app/assets/stylesheets/partials/_responsive.scss
- app/assets/stylesheets/partials/_searchbar.scss
- app/assets/stylesheets/partials/_vars.scss
- app/controllers/pages_controller.rb
- app/models/concerns/input_cleaner.rb
- app/views/application/_highlights-row.html.erb
- app/views/application/_home-row.html.erb
- app/views/application/_responsive-search-options.html.erb
- app/views/application/_search-options.html.erb
- app/views/pages/ambler.html.erb
- app/views/pages/home.html.erb
- app/views/pages/hsl.html.erb
Using the mock-up for the homepage, please create a mobile version. You can use an iPhone sample device.
***** NOTE: this adversely affects the mini-homepages responsive design, but since their entire design is being redone, this should be ok and future tickets will address their responsiveness ******
- Add responsive styling for Highlights section of homepage
- Add responsive styling for static  homepage blocks
- Update search options and hours info for responsive design
- Updates to pass tests (add strip to description cleaner) and fix some alignments.
- updates to hsl and ambler homepages to not render quite so badly at low res
> Homepage Responsive Design

- app/views/pages/ambler.html.erb
#MAN-173 Change_link_name_Ambler_homepage
On the yellow secondary nav, update the "Ambler Campus Library" link to read "Ambler Campus Library Information"
***************************
Updated text
> #MAN-173 Change_link_name_Ambler_homepage

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_vars.scss
- app/assets/stylesheets/policies.scss
- app/dashboards/policy_dashboard.rb
- app/fields/description_field.rb
- app/models/ability.rb
- app/views/application/_footer.html.erb
- app/views/policies/show.html.erb
- spec/views/policies/show.html.erb_spec.rb
#MAN-154 Code policy entity display
- Update view and styles for the Policy show page according to design…mockups.
- Adjust time formats in tests to pass
> #MAN-154 Code policy entity display

- app/assets/stylesheets/application.scss
- app/views/spaces/_services.html.erb
- spec/views/persons/index.html.erb_spec.rb
#MAN-164 
Please add a header row on the space entity page below the picture and description, but above the related service.
- Add services heading to space page
- Update code to better reference related services
> #MAN-164 missing services heading

- app/services/sync_service/blogs.rb
- app/views/blog_posts/index.html.erb
- app/views/blog_posts/show.html.erb
- app/views/blogs/index.html.erb
- app/views/blogs/show.html.erb
- config/brakeman.ignore
- lib/tasks/blogs_sync.rake
Address issues #MAN-52 and #MAN-53
> MAN-52 MAN-53 rake task for blog sync service

- app/views/policies/index.html.erb
> Update page name.

- app/controllers/admin/blogs_controller.rb
- app/dashboards/blog_dashboard.rb
- app/services/sync_service/blogs.rb
- app/views/admin/blogs/_collection.html.erb
- app/views/admin/blogs/index.html.erb
- config/locales/en.yml
- config/routes.rb
- db/schema.rb
Addresses Issue #MAN-54 to add ability to sync a single blog selected from the dashboard.
> MAN-54 Add sync selected blog capability to dashboard

- Dockerfile
- app/controllers/accounts/omniauth_callbacks_controller.rb
- app/controllers/admin/accounts_controller.rb
- app/controllers/admin/alerts_controller.rb
- app/models/concerns/validators.rb
- app/services/sync_service/events.rb
- app/views/admin/application/_navigation.html.erb
- app/views/admin/blogs/index.html.erb
- app/views/admin/events/index.html.erb
- app/views/mail_form/contact.erb
- config/locales/en.yml
- db/schema.rb
- docker-compose.yml
- spec/models/blog_spec.rb
- spec/models/building_spec.rb
- spec/models/group_spec.rb
- spec/models/space_spec.rb
Addresses issue #MAN-83: Global replace references to fortytude
> MAN-83 Replace `fortytude` with `manifold`

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/buildings.scss
- app/assets/stylesheets/partials/_responsive.scss
- app/assets/stylesheets/policies.scss
- app/assets/stylesheets/services.scss
- app/assets/stylesheets/spaces.scss
- app/views/events/_visit.html.erb
- app/views/groups/_visit.html.erb
- app/views/spaces/_policies.html.erb
- app/views/spaces/_services.html.erb
- app/views/spaces/_visit.html.erb
- app/views/spaces/responsive/_policies.html.erb
- app/views/spaces/responsive/_services.html.erb
- app/views/spaces/responsive/_visit.html.erb
- app/views/spaces/show.html.erb
#MAN-115 Space entity responsive version - time to build
Please apply design to the responsive space entity
*****************************
Create partials for responsive rows and adjusted styles according to design. Rachel said not to use the purple from the design.
> #MAN-115 Space entity responsive version

- app/assets/stylesheets/buildings.scss
- app/assets/stylesheets/partials/_responsive.scss
- app/assets/stylesheets/policies.scss
- app/assets/stylesheets/spaces.scss
- app/views/buildings/_collections.html.erb
- app/views/buildings/responsive/_collections.html.erb
- app/views/buildings/responsive/_spaces.html.erb
- app/views/buildings/responsive/_visit.html.erb
- app/views/buildings/show.html.erb
- app/views/groups/responsive/_visit.html.erb
- app/views/groups/show.html.erb
#MAN-114
Create a responsive version of the building entity page
****************************
Add partials and styling for responsive handling on Buildings. 
Also consolidate the way partials work for responsive across the other models with existing responsive designs in place.
> #MAN-114 Building entity responsive

- app/controllers/library_hours_controller.rb
- app/views/library_hours/index.html.erb
- lib/tasks/hours_ingest.rake
#MAN-221
Steven has requested to have the following column added to the New Charles
Library spreadsheet: Service Zone
NOTE:  Can you please make all  the columns the same width because the SCRC
column (plus café looks like it might be too short too) is cutting off
information.  The spreadsheet won’t allow me to make the change(s) and says
to contact spreadsheet owner.
*********************************
Resized columns
Added new column
Update hours app to use new Charles based location names and hours
> #MAN-221 Charles Library Hours Spreadsheet

- app/views/application/_home-row.html.erb
#MAN-195 Add Link to Scholars Studio
Please add a link to the Scholar's studio mini homepage to the yellow navigation box. It can be a text placeholder until their mini homepage is done.
***************************************************
Added link to homepage.
> #MAN-195 Add Link to Scholars Studio

- db/schema.rb
> Remove stray schema changes

- app/assets/stylesheets/partials/_typography.scss
- app/controllers/admin/library_hours_controller.rb
- app/controllers/buildings_controller.rb
- app/controllers/library_hours_controller.rb
- app/controllers/spaces_controller.rb
- app/dashboards/library_hour_dashboard.rb
- app/models/building.rb
- app/models/library_hour.rb
- app/models/service.rb
- app/models/space.rb
- app/services/sync_service/library_hours.rb
- app/views/admin/library_hours/_collection.html.erb
- app/views/admin/library_hours/index.html.erb
- app/views/library_hours/index.html.erb
- config/locales/en.yml
- config/routes.rb
- lib/tasks/hours_sync.rake
- spec/controllers/library_hours_controller_spec.rb
- spec/factories/library_hour.rb
- spec/models/library_hour_spec.rb
#MAN-55 Refactor Hours implementation
- move the logic into a service Object
- Call the service object from Rake
- Allow the service object to be called from a Admin Dashboard.
- Add tests for the service object
********************************************
Update hours controller and views
Move google logic to service
Add sync button to new hours dashboard
Correct singularization of LibraryHours to Library Hour (helpers and tests)
Everything except the test on the service
> #MAN-55 Refactor Hours implementation

- app/views/pages/form-other.html.erb
- app/views/pages/orgchart.html.erb
- app/views/pages/publication.html.erb
- app/views/pages/statement.html.erb
#MAN-264 Page entity - type appears in title
In the page entity, the page type is showing up in the display of the title field.
Removed page type from page display.
> #MAN-264 Page entity - type appears in title

- app/assets/stylesheets/administrate/components/_buttons.scss
- app/dashboards/category_dashboard.rb
- app/views/admin/application/_form.html.erb
- app/views/admin/application/show.html.erb
Move the "View in Website" button to Show Nav menu, and make it green.
> Man 212 user feedback and bugfix

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/buildings.scss
- app/assets/stylesheets/events.scss
- app/assets/stylesheets/partials/_card-rows.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_responsive.scss
- app/assets/stylesheets/partials/_searchbar.scss
- app/assets/stylesheets/partials/_vars.scss
- app/assets/stylesheets/policies.scss
- app/assets/stylesheets/spaces.scss
- app/views/application/_header_navbar.html.erb
- app/views/application/_responsive-search-options.html.erb
- app/views/application/_search-options.html.erb
- app/views/policies/show.html.erb
#MAN-248 Restyle website header to match design mockup
Add search to header.
Move main nav to green bar.
Finish desktop (1200px and higher) positioning.
Update searchbox classes for tablet view positioning.
Update for responsive styling under 1200px.
Add submenu on Policies page as example for sub-pages.
> #MAN-248 Restyle website header to match design mockup

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_responsive.scss
- app/assets/stylesheets/partials/_searchbar.scss
- app/models/page.rb
- app/views/application/_header-search.html.erb
- app/views/application/_header_navbar.html.erb
- app/views/application/_page-search.html.erb
- app/views/application/_responsive-search-options.html.erb
- app/views/application/_search-options.html.erb
- app/views/pages/home.html.erb
Add separate search field for pages, outside the header
Adjustments per ticket comments
Adjustments for responsive flow
> #MAN-249 Homepage Header

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_categories.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_searchbar.scss
- app/controllers/pages_controller.rb
- app/views/application/_header_navbar.html.erb
- app/views/application/_responsive-search-options.html.erb
- app/views/application/_search-options.html.erb
Update styles for homepage searchbar with options and top search in mobile.
> #MAN-249 Fixes

- app/assets/javascripts/application.js
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/services.scss
- app/controllers/pages_controller.rb
- app/views/application/_mobile-nav.html.erb
- app/views/application/_page-search.html.erb
- app/views/services/_mobile_menu.html.erb
- app/views/services/show.html.erb
#MAN-283 
***********************
Updates/additions from ticket after initial merge.
> #MAN-283 code services entity page

- app/controllers/admin/external_links_controller.rb
- app/dashboards/external_link_dashboard.rb
- app/models/external_link.rb
- config/routes.rb
- db/migrate/20190513174221_create_external_links.rb
- db/schema.rb
- spec/factories/external_links.rb
- spec/models/external_link_spec.rb
Issue #MAN-282
- Add external_link entity
- Add external_link dashboard
- Make categorizable
> MAN-282 External link entity

- app/dashboards/external_link_dashboard.rb
> MAN-282 Add categories to external links admin dashboard

- app/serializers/building_serializer.rb
- app/serializers/concerns/image_serializable.rb
- app/serializers/event_serializer.rb
- app/serializers/person_serializer.rb
> Refactor serialized objects with images to concern

- config/routes.rb
Removed non-administrate routes for alerts.
> #MAN-273 Remove non-admin route resources for Alerts

- app/models/form.rb
- app/views/forms/data-purchase-grants-application/_request-info.html.erb
- app/views/forms/data-purchase-grants-application/_title.html.erb
- app/views/forms/shared/_personal_info.html.erb
> #MAN-274 Create form for Library Data Grant application

- app/serializers/concerns/image_serializable.rb
> Constructs imageable route concern in image serializer

- app/dashboards/external_link_dashboard.rb
- app/dashboards/service_dashboard.rb
- app/models/service.rb
- db/migrate/20190520202839_add_external_link_to_services.rb
- db/schema.rb
- spec/models/service_spec.rb
> MAN-309 Add external_link to services

- app/views/services/show.html.erb
Exchanged access link for external link in services show.
> #MAN-341 Service Entity Display External Link

- app/models/category.rb
- app/models/concerns/categorizable.rb
- spec/models/category_spec.rb
- spec/support/categorizable_spec.rb
When a category or categorized is deleted, delete the associated
categorization as well.
> Delete dependent categorizations.

- app/dashboards/building_dashboard.rb
- app/models/building.rb
- db/migrate/20190523193908_add_external_link_to_buildings.rb
- db/schema.rb
- spec/models/building_spec.rb
> MAN-345 Add external_link to buildings

- app/views/admin/categories/show.html.erb
> MAN-314: Display list of entities with categories

- app/dashboards/category_dashboard.rb
- db/migrate/20190524142559_add_description_to_categories.rb
- db/schema.rb
- spec/factories/categories.rb
- spec/models/category_spec.rb
> MAN-316 Add description field to category

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/persons.scss
- app/controllers/persons_controller.rb
- app/views/persons/_desktop.html.erb
- app/views/persons/_mobile.html.erb
- app/views/persons/show.html.erb
Talk to Rachel if you have questions!
Refactored person show page per design for desktop
Updated show page for responsive design
Included css logic to pull a partial for desktop or responsive since mobile design requested a different html structure than desktop
> #MAN-370 Code People Entity Page

- app/controllers/library_hours_controller.rb
- config/application.rb
Fixes hours display issue by removing buildings array structure from config and putting it back in the controller.
> Hours Fix: can't modify shared data

- .travis.yml
What this PR does:
- adds a travis pre_install step that installs bundler based on the version the Gemfile.lock was created for
> adding bundle install for the bundler version used in gemfile.lock

- README.md
- app/models/concerns/input_cleaner.rb
- app/models/person.rb
- app/views/persons/_desktop.html.erb
- app/views/persons/_mobile.html.erb
- spec/features/person_spec.rb
- spec/models/person_spec.rb
Issue: #381
Created to fix possible harvest issues
Remove feature spec after we've verified this works and hasn't broken any of the views.
> MAN-381 Remove blank specialty in people records

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- config/database.yml
- db/schema.rb
- spec/factories/blog_posts.rb
- spec/rails_helper.rb
- spec/services/sync_events_spec.rb
Switches the DB adapter to postgres, sets up travis to test using postgres, and fixes some test that failed because of postgres data constraints / auto-increment.
Also adds set up instructions for getting PG set locally for development work.
> Switch db to postgresql

- app/views/application/_mobile-menu-items.html.erb
- app/views/buildings/_categories.html.erb
- app/views/buildings/_mobile_categories.html.erb
- app/views/pages/_items.html.erb
- app/views/services/_all_services.erb
- app/views/spaces/_all_spaces.html.erb
Reverts tulibraries/manifold#499
HoneyBadger reports: ActionView:Template Error: undefined method 'url' https://app.honeybadger.io/projects/58150/faults/51131833
> Revert "Error on linode when external link added to a space"

- app/views/application/_mobile-menu-items.html.erb
- app/views/buildings/_categories.html.erb
- app/views/policies/_all_policies.html.erb
Fix policy nav trying to set selected on @space
> Clean up some duplicated code.

- app/views/collections/_category_items.html.erb
- app/views/pages/_items.html.erb
- app/views/services/_all_services.erb
- app/views/spaces/_categories.html.erb
Remove the word menu from pages leftside index. 
Refactored all leftside indexes, and excluded items that are categories.
> Leftside Index Tweaks

- .travis.yml
- app/controllers/finding_aids_controller.rb
Was trying to sort on title, but that column doesn't exist.
Fixes https://app.honeybadger.io/projects/61880/faults/51909701
> Switch finding aid to sort on name

- .travis.yml
Fixes a pyenv compile issue with 3.7.2
> Downgrade python 3.6.6 for deploys

- app/controllers/pages_controller.rb
- app/views/pages/hsl.html.erb
Adjust query for building to using sql matching. 
Update view to handle nil values on buildings if there are no matches.
> HSL homepage fixes

- app/views/application/_footer.html.erb
Updates call to social links page from footer.
> Social Media link in footer

- app/assets/stylesheets/events.scss
- app/views/events/_events.html.erb
Event page coded, index page tweaks.
> #MAN-437 Code exhibit page entity

- app/dashboards/category_dashboard.rb
- app/dashboards/external_link_dashboard.rb
- app/dashboards/page_dashboard.rb
- app/dashboards/service_dashboard.rb
- app/dashboards/space_dashboard.rb
- db/migrate/20190715190407_add_slug_to_pages.rb
- db/migrate/20190715191411_add_slug_to_events.rb
- db/migrate/20190715191430_add_slug_to_external_links.rb
- db/migrate/20190715191441_add_slug_to_categories.rb
- db/migrate/20190715191501_add_slug_to_spaces.rb
- db/migrate/20190715191512_add_slug_to_services.rb
- db/schema.rb
It would be helpful to have slugs for a number of Entities so it is
easier to link to them from static sources like Controllers.
Add slugs column to Pages, Events, External Links, Categories, Spaces,
and Services.
Add slug filed to the admin form for these as well.
> Invasion of the slugs

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/partials/_header.scss
- app/views/application/_header_navbar.html.erb
- app/views/pages/home.html.erb
In response to coments:
Removed searchbar toggle from header in responsive views.
Added searchbar always present under main menu in responsive views.
Adjusted header logo to vertically align in smaller responsive views.
Added todays hours widget to header in smaller responsive views.
> #MAN-416 Code the homepage

- app/assets/stylesheets/forms.scss
From #MAN-403:
But based on the ones I saw, we just  need the button changed from blue to teal Chris Doyle  thanks!
***********************
Updated color of submit button
> Submit button color change (forms only)

- app/controllers/admin/buildings_controller.rb
- app/controllers/admin/collections_controller.rb
- app/controllers/admin/events_controller.rb
- app/controllers/admin/exhibitions_controller.rb
- app/controllers/admin/groups_controller.rb
- app/controllers/admin/highlights_controller.rb
- app/controllers/admin/pages_controller.rb
- app/controllers/admin/people_controller.rb
- app/controllers/admin/spaces_controller.rb
- app/controllers/concerns/admin/detachable.rb
- app/dashboards/collection_dashboard.rb
- app/views/fields/document_field/_form.html.erb
- app/views/fields/file_field/_form.html.erb
- app/views/fields/photo_field/_form.html.erb
- config/brakeman.ignore
- config/locales/en.yml
- config/routes.rb
- spec/factories/groups.rb
- spec/factories/pages.rb
- spec/rails_helper.rb
- spec/requests/admin/building_spec.rb
- spec/requests/admin/event_spec.rb
- spec/requests/admin/exhibition_spec.rb
- spec/requests/admin/group_spec.rb
- spec/requests/admin/highlight_spec.rb
- spec/requests/admin/page_spec.rb
- spec/requests/admin/person_spec.rb
- spec/requests/admin/space_spec.rb
- spec/support/detachable_spec.rb
> MAN-266 detach attachments

- app/views/pages/scrc.html.erb
Added image extension to icons in view.
> SCRC homepage icons

- app/controllers/pages_controller.rb
- app/views/pages/contact/_four.html.erb
- app/views/pages/contact/_one.html.erb
Please link the “Frequently called numbers” to https://web.qa.tul-infra.page/pages/19
Please link the “Find your subject librarian” to https://web.qa.tul-infra.page/people?page=1&specialists=true
> #MAN-363 Contact us Index page links

- app/schemas/collection_schema.json
- app/schemas/exhibition_schema.json
- app/schemas/finding_aid_schema.json
- app/schemas/group_schema.json
- app/schemas/page_schema.json
- app/schemas/policy_schema.json
- app/schemas/service_schema.json
- app/schemas/space_schema.json
- app/serializers/application_serializer.rb
- app/serializers/building_serializer.rb
- app/serializers/collection_serializer.rb
- app/serializers/concerns/link_serializable.rb
- app/serializers/event_serializer.rb
- app/serializers/exhibition_serializer.rb
- app/serializers/finding_aid_serializer.rb
- app/serializers/group_serializer.rb
- app/serializers/page_serializer.rb
- app/serializers/person_serializer.rb
- app/serializers/policy_serializer.rb
- app/serializers/service_serializer.rb
- app/serializers/space_serializer.rb
Add the link concern to all serializers where appropriate.
Cleans up some includes for serializers so all includes at the top of the class.
Updates schemas to reflect the inclusion of links in the json
response.
> Refactors a link concern for serializers

- Gemfile
- Gemfile.lock
- spec/controllers/admin/events_controller_spec.rb
- spec/factories/accounts.rb
- spec/factories/persons.rb
- spec/rails_helper.rb
Use rails rspec built in transactions instead.
> Remove database cleaner

- app/assets/stylesheets/pages.scss
- app/controllers/persons_controller.rb
- app/views/persons/index.html.erb
On the Staff directory, there is a call-out box for "Frequently called numbers". That box should link to https://web.qa.tul-infra.page/pages/19.
Also, please update the “Main phone” to read 215-204-0744
> #MAN-419 On staff directory page, add link to Frequently called numbers

- app/assets/stylesheets/partials/_hours.scss
- app/helpers/library_hours_helper.rb
- app/views/library_hours/_desktop.html.erb
- app/views/library_hours/_mobile.html.erb
- app/views/library_hours/index.html.erb
please link the building and space names to their respective building and space pages if they exist.
*************************
Add partials for desktop and mobile rendering
Apply design styles from mockups
Add links to location names
> #MAN-455 Update Library hours desktop and mobile

- app/models/form.rb
Please add Steven Bell (bells@temple.edu) and Richie Holland (richieh@temple.edu) as recipients for the IR form on the new website.
****************************
Added richie and stevenb to IR form recipients.
> #MAN-457 Send IR form to recipients

- app/views/application/_footer.html.erb
Added staff form link to footer.
> #MAN-409 Add link to footer for staff forms

- app/assets/stylesheets/blogs.scss
- app/assets/stylesheets/hsl.scss
- app/controllers/blogs_controller.rb
- app/models/concerns/imageable.rb
- app/views/blogs/index.html.erb
- app/views/pages/home.html.erb
- config/brakeman.ignore
Update News link on homepage to go to blogs_path
> #MAN-454 Code Blogs and News page

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/aws_credentials.rb
- config/storage.yml
- spec/initializers/aws_credentials_spec.rb
Adds tests to make sure the config is picked up.
> Switch Active Storage to Use S3

- app/assets/stylesheets/pages.scss
- app/controllers/admin/categories_controller.rb
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/dashboards/blog_dashboard.rb
- app/dashboards/building_dashboard.rb
- app/dashboards/category_dashboard.rb
- app/models/category.rb
- app/models/form.rb
- app/views/library_hours/show.html.erb
- app/views/pages/home.html.erb
- app/views/pages/hsl.html.erb
- app/views/persons/_department.html.erb
- config/routes.rb
- db/migrate/20190719141523_add_slug_to_buildings.rb
- db/migrate/20190719141541_add_slug_to_blogs.rb
- db/schema.rb
- spec/factories/categories.rb
- spec/models/category_spec.rb
- spec/requests/admin/category_spec.rb
- spec/support/categorizable_spec.rb
Updated model and dashboard of Categpry to use image rather than icon
Adjust spec tests to reflect icon name change
Added alias route "news" to render "blogs" index
Updated instance variables on views and contollers to use slugs
> Added slug field to building and blog models

- spec/controllers/images_controller_spec.rb
A race condition in the person factory when we add an image was causing a test to fail. Fixe it with sleep.
https://www.youtube.com/watch?v=yukcIejMG2c
> Beautiful kitten fish, sleep baby sleep

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/_pagination.scss
- app/assets/stylesheets/partials/_responsive.scss
- app/assets/stylesheets/partials/_searchbar.scss
Correct a few vars import statements in other partials.
> Updated application.scss to not use imports for partials.

- app/views/blogs/index.html.erb
Update blog links to go to external blog
> #MAN-454 Code Blogs & News page

- app/controllers/forms_controller.rb
- app/serializers/form_serializer.rb
- app/views/forms/data-purchase-grants-application/_title.html.erb
- app/views/forms/hsl-book-reserve/_title.html.erb
- app/views/forms/index.html.erb
- app/views/forms/ir/_title.html.erb
- app/views/forms/missing-book/_title.html.erb
- app/views/forms/purchase-request/_title.html.erb
- app/views/forms/recall-book/_title.html.erb
- config/locales/en.yml
- forms-readme.md
- swagger/swagger.json
Construct JSON response for forms.
Alters the way we create forms, by requiring they have their title in
the localizations file.
> JSON response for forms.

- app/models/form.rb
- app/views/forms/_all.html.erb
- app/views/forms/index.html.erb
- app/views/forms/proxy-account/_intro.html.erb
- app/views/forms/proxy-account/_request-info.html.erb
- config/locales/en.yml
You recently created a proxy form in Drupal for Kathy. Please replicate in Manifold.
https://library.temple.edu/services/forms/proxy-account
Added Proxy Account form
> #MAN-386 Replicate Proxy Form in Manifold

- app/views/pages/tudsc.html.erb
> #MAN-439 Code the Scholars Studio mini homepage

- app/views/pages/home.html.erb
updating "Search the catalog" to "Search our collections"
Updated link text
> MAN-479 Search the catalog text

- app/views/pages/home.html.erb
> #MAN-495 Update "Health Science Library" on homepage

- app/assets/javascripts/jumble.js
- app/assets/stylesheets/partials/_mainmenu.scss
- app/assets/stylesheets/partials/_mobilemenu.scss
- app/views/application/_header_navbar.html.erb
- app/views/application/_mobile-nav.html.erb
- app/views/layouts/application.html.erb
We need to link the LibAnswers chat on the primary navigation bar.
*************************
Added chat widget button via JS to all pages in main menu. 
Update jumble.js to add chat widget to mobile menu.
> #MAN-494 Link to chat box on primary nav

- app/assets/stylesheets/mini-pages.scss
- app/views/pages/hsl.html.erb
"Contact Us" button
1. Replace "Contact us" with 215-707-2665
2. Remove the link
3. Keep the phone icon
Add a new teal button (red is the new teal)
1. Label: "Chat with a Health Science Librarian"
2. Link: TBD - will go to a springshare chat box.
***********************
Added new chat box with dummy link, to be filled in later
> #MAN-482 Updates to HSL mini homepage

- app/views/pages/scrc.html.erb
> #MAN-500 Update SCRC Catalog results

- app/controllers/pages_controller.rb
Updated controller variable to pull collections from SCRC Collecting Emphases category rather than all collections.
> #MAN-499 Update Collecting Emphases on SCRC mini homepage

- app/controllers/application_controller.rb
- app/dashboards/policy_dashboard.rb
- app/views/application/_footer.html.erb
- db/migrate/20190726193547_add_slug_to_policies.rb
- db/schema.rb
Please update the following links in the footer: 
Diversity Statement: /pages/3
Community Standards: /policies/9
Virtual Reference Services: 
add link to /services/57 
update title to read "Virtual Reference Privacy Guidelines"
Privacy Guidelines: remove this link 
Updated footer links per ticket.
Added slug field to policies
slugs => label:
Page.find_by_slug("diversity") => "TULUP Diversity Statement"
Policy.find_by_slug("standards") => "Temple University Libraries Community Standards"
Service.find_by_slug("privacy") => "Virtual Reference privacy guidelines"
> #MAN-496 Footer links

- app/views/layouts/application.html.erb
Page: web.qa.tul-infra.page
Path: html
Snippet: <html>
Added english as html element lang attribute
> #MAN-507 html-has-lang: HTML element must have a lang attribute

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/partials/_footer.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_mobilemenu.scss
- app/assets/stylesheets/partials/_searchbar.scss
- app/assets/stylesheets/partials/_typography.scss
- app/assets/stylesheets/persons.scss
- app/assets/stylesheets/services.scss
- app/views/pages/home.html.erb
Throughout website:
Change fonts: (these are google fonts)
- Roboto Condensed for headers
- Faustina for body
Homepage:
Change "Explore Charles" to "Explore Charles Library"
************************
Updated fonts globally. 
Changed link text on homepage.
> #MAN-515 Stratcomm edits to the website

- app/assets/stylesheets/forms.scss
- app/views/application/_header-search.html.erb
- app/views/application/_mobile-search.html.erb
Added labels to Search everything forms not generated by Rails.
Added style to hide labels but keep available for screen readers.
> MAN-509 Form elements must have labels

- app/assets/stylesheets/pages.scss
- app/views/pages/hsl.html.erb
Update the Chat link with this code from Springshare:
<script type="text/javascript" src="https://v2.libanswers.com/load_chat.php?hash=d608b96235d521d5947815fa1dfe16b8"></script>
<div id="libchat_d608b96235d521d5947815fa1dfe16b8"></div>
Updated chat link on HSL mini page
> MAN-517 Update HSL mini homepage

- app/views/application/_header_navbar.html.erb
- app/views/application/_mobile-nav.html.erb
- app/views/pages/hsl.html.erb
Updated chat button on main menu.
> Add chat widget link to main menu

- app/views/forms/_all.html.erb
- app/views/forms/recall-book/_request-info.html.erb
- config/locales/en.yml
On the "recall-book" form, please change the pickup location of "Paley" to "Charles"
Changed all instances of Paley to Charles
> #MAN-519 Recall book form - Change Paley

- app/views/application/_header-search.html.erb
- app/views/application/_mobile-search.html.erb
- app/views/application/_page-search.html.erb
Updated form labels for search everything.
> #MAN-509 Form elements must have labels

- app/assets/stylesheets/pages.scss
- app/controllers/pages_controller.rb
- app/views/pages/scrc.html.erb
Additions: 
1. Browse finding aids - link to /finding_aids 
2. Add a button labeled “Hours & Info” with the “i” icon that Rachel Cox provides and link to /spaces/11 - this page has the hours. We’re not going to put the hours directly on the mini homepage, at least not for the MVP. 
3. Please update the “Contact us” box to link to the Ask SCRC form located at ‘/forms/ask-scrc’
Updated and added links to scrc page.
> #MAN-438 Code SCRC mini homepage

- app/views/pages/home.html.erb
> #MAN-527 Remove apostrophe from Duckworth Scholars Studio

- app/views/forms/_all.html.erb
Removed the requested form listing.
> #MAN-529 Remove form from list of forms

- app/views/pages/home.html.erb
Update the full name to “Loretta C. Duckworth Scholars Studio”
Updated name for DSC on homepage.
> #MAN-527 Remove apostrophe form Duckworth Scholars Studio

- app/models/category.rb
Add imageable concern to Category model. 
Remove image field from model.
View was not finding image.attachment  before these changes.
> Category Icon Fix

- app/controllers/library_hours_controller.rb
- app/services/sync_service/library_hours.rb
Please add the following areas:
24/7 Space
Add 24/7 Space to hours under CharlesAdd 24/7 Space to hours under Charles
> #MAN-489 Charles Library Website Hours Change

- app/controllers/application_controller.rb
Update footer variable for donations to look for Policy rather than Page.
******************
Updated variable to query policies for donations slug
> #MAN-562 Update Donations button slug

- app/views/application/_footer.html.erb
Please connect the social media buttons to link to /pages/18
***************************
Updated link of icons in footer to use instance variable.
> #MAN-547 Social Media links go to events page

- app/assets/stylesheets/mini-pages.scss
Increase spacing between list items.
> #MAN-555 Font on HSL page

- app/assets/stylesheets/partials/_mobilemenu.scss
fix alignment issue (see ticket for screenshot)
Change secondary menu font heading to Roboto to match the desktop version
Updated css for responsive menu behavior
> #MAN-563 secondary menu error on mobile

- app/models/form.rb
Re-update the recipients for SCRC instruction form. Previous work was most likely corrected out during a conflict resolution.
> Re-update the recipients for SCRC instruction form

- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/partials/_header.scss
- app/views/application/_header_navbar.html.erb
- app/views/pages/home.html.erb
Adjust styles and html to accommodate wrapping logo text in responsive views.
> #MAN-483 Mobile header wrapping

- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/partials/_searchbar.scss
The top madding or margin on the homepage does not match the rest of the pages.. when you leave the homepage you can see the logo and title shift down about 10-20 px.
******************
Adjust padding on header elements for greater consistency across all pages.
> #MAN-566 Fix padding/margins

- app/assets/stylesheets/partials/_footer.scss
font in footer is hard to read
Increase font size in footer.
> #MAN-548 Increase font size in footer

- app/views/application/_building_hours.html.erb
- app/views/application/_building_mobile_hours.html.erb
- app/views/application/_space_hours.html.erb
- app/views/application/_space_mobile_hours.html.erb
> #MAN-568 Change text on see more hours button

- app/assets/stylesheets/pages.scss
Fixed alignment issue for Firefox responsive view.
NOTE: the 3px overlap is intentional and will not be changed.
> MAN-533 Fix Misaligned Main Search Button

- app/models/form.rb
- app/views/forms/_all.html.erb
- app/views/forms/shared/_personal_info.html.erb
- app/views/forms/table-request/_intro.html.erb
- app/views/forms/table-request/_request-info.html.erb
- config/locales/en.yml
- spec/requests/forms/table_request_spec.rb
> #MAN-523 Update Tabling Request Form

- app/assets/stylesheets/pages.scss
- app/views/pages/home.html.erb
1. Change "News" and "Events" link  text on homepage mobile display from white to black
2. fix alignment (items in red boxes and not left aligned with other content)
***********************
Updated color of News and Events text. 
Corrected alignment of icons in mobile view.
> #MAN-584 homepage mobile changes

- app/views/persons/index.html.erb
> #MAN-582 Update staff directory Main Phone

- app/controllers/pages_controller.rb
- app/views/pages/charles.html.erb
This page needs to hard code both the page and the external link to show text and show the nav menu.
> Fix explore chalres with ExternalLink

- .travis.yml
- .travis/deploy-prod.sh
What this PR does:
- for Travis deploy, runs deploy prod script when there is a git tag (note: **any** tag) & it has form v{digit}{whatever}. 
- changes the prod deploy script to pass in the TRAVIS_TAG (git tag) to the playbook as the 'rails_app_git_branch' variable, overriding the default in the playbook
> adding git tag check for prod deployment

- .travis.yml
- .travis/deploy-prod.sh
Tag regex check before was looking for only `v{integers}`.
> adding log statement for prod deploy script; & fixing tag regex

- app/views/application/_footer.html.erb
- config/locales/en.yml
- config/routes.rb
Please add a link in the footer: 
link name/title: Patron Forms
link destination: https://library.temple.edu/forms
> #MAN-600 Add link to forms to footer

- app/assets/stylesheets/videos.scss
- app/controllers/pages_controller.rb
- app/views/events/index.html.erb
- app/views/pages/_videos.html.erb
- app/views/pages/videos_all.html.erb
- app/views/pages/videos_list.html.erb
- app/views/pages/videos_search.html.erb
- app/views/pages/videos_show.html.erb
- config/application.rb
- config/routes.rb
We need to replicate this page: http://oak.library.temple.edu/watchpastprograms
****************
Create new set of pages based on old program video pages
Use a model-less approach and pull all content from API
NOTE: ENVIRONMENT VARIABLES NEED TO BE SET. Search LastPass for "ensemble api"
> #MAN-166 List of Videos

- app/views/pages/contact/_three.html.erb
> #MAN-618_Links on the Contact Us page

- app/models/form.rb
Added additional recipient to purchase form
> #MAN-614 Purchase request form email

- app/models/form.rb
- app/views/forms/event-space-request/_request-info.html.erb
- app/views/forms/index.html.erb
- app/views/forms/shared/_personal_info.html.erb
- config/locales/en.yml
- spec/requests/forms/event_space_request_spec.rb
Attaching the updated word doc for requesting Charles spaces. Can we get this converted to a form  for the site? Do not hesitate to contact me with any questions or concerns about formatting or anything like that.
> #MAN-627 Charles Spaces Request form

- app/assets/stylesheets/persons.scss
- app/views/persons/_mobile-menu.html.erb
I have one small revision: Chris Doyle Please center the text vertically in these buttons on the results page. The text should skooch up a smidge.
Also the filter icon is still green until you click it.
**********************
Adjusted padding. Updated filter icon.
> #MAN-448 Staff directory display and cleanup modifications

- app/views/layouts/application.html.erb
cynthiag@temple.edu sent you a message and needs your help installing Crazy Egg on library.temple.edu.
--
Hi Chris, I want to set up click tracking on the new website. Can you put this in place for me, please!
Installing Crazy Egg is easy!
Paste the JavaScript tag into the <head> of your website.
<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0088/8647.js" async="async"></script>
> #MAN-639 Add Crazy Egg Click Tracking Script

- Gemfile
- Gemfile.lock
For switching our env var support over to it
> Add dotenv

- app/views/forms/event-space-request/_request-info.html.erb
Under “Room Setup”, you have a field labeled “Event date” but with a drop-down for the room setup options.
> #MAN-627 Charles Spaces request

- app/assets/stylesheets/partials/_footer.scss
IA requested the button be bigger than before so I’m fine with 22 or 20, it's your call. 
(Donate button in footer)
> #MAN-624 Create new Support the Libraries button for footer

- app/models/form.rb
- app/views/forms/graduate-locker-request/_intro.html.erb
- app/views/forms/index.html.erb
- app/views/forms/shared/_personal_info.html.erb
- config/locales/en.yml
- spec/requests/forms/graduate_locker_request_spec.rb
I'd like a Google form be created for the lockers in the graduate studio.
I'd like the form to direct to Marianne's e-mail address, mmoll@temple.edu
please.
The form should contain the following information and fields please.
Charles Library Graduate Studio Locker Request Form
Lockers are available on a first-come/first-served basis for graduate
students and faculty in the Charles Library. Due to high demand and the
limited number of lockers (32), we cannot guarantee that a locker will be
available to each patron who makes a request. We will email you to let you
know if a locker is available once we receive your request.
Your information (all fields are required):
First Name­­­­­­­­­­­­­­­­­­­­­­­____________________________________
Last Name____________________________________ *TUid …
> #MAN-648 Google form request

- config/locales/en.yml
Cynthia Schwarz
24 minutes ago
I’m still seeing 215-204-8231. I’m looking at QA.
Chris Doyle
2 minutes ago
This was overwritten by a subsequently merged ticket: #MAN-625 which did not have the updated info. 
Updated phone number in config
> #MAN-643 update phone number on footer

- app/assets/stylesheets/forms.scss
- app/models/form.rb
- app/views/forms/partners-borrowing/_intro.html.erb
- app/views/forms/partners-borrowing/_request-info.html.erb
- app/views/forms/shared/_personal_info.html.erb
- config/locales/en.yml
- spec/requests/forms/partners_borrowing_spec.rb
Could you please add the Partners Borrowing Privileges form to the new
website?
************
original: https://web.old.tul-infra.page/services/forms/partners-borrowing
new: https://web.qa.tul-infra.page/forms/partners-borrowing
> #MAN-666 Partners Borrowing Privileges form on website

- app/controllers/concerns/finding_aids_finder.rb
Reversed the conditional check in finding aids concern.
> #MAN-520 Collection entity "Explore this collection" button

- app/views/pages/videos_search.html.erb
Sanitized display of user-based input on event video search page.
> #MAN-689 Search Term Display

- app/controllers/pages_controller.rb
Pagination in the video's page has a logic error when there is no page defined 
https://github.com/tulibraries/manifold/blob/master/app/controllers/pages_controller.rb#L23
raised by https://app.honeybadger.io/projects/61882/faults/55224818
> #MAN-688 Pagination error in Videos

- app/controllers/collections_controller.rb
- app/controllers/services_controller.rb
- spec/factories/collections.rb
- spec/factories/redirects.rb
- spec/requests/collections_spec.rb
- spec/requests/services_spec.rb
Allows redirects at /collections/* and /services/* to work
> Add redirect support for collection and service

- app/views/pages/charles.html.erb
Previous work on cleaning up category displays across models left call to left-side category menu with old filename on the Explore Charles template. Updated file name and page renders.
> Explore Charles Page Fix

- app/views/pages/charles.html.erb
Use items partial instead of categories
> Fix Charles nav menu

- app/controllers/pages_controller.rb
- app/views/pages/videos_all.html.erb
Also addresses: 
#MAN-697 Links on Video homepage
#MAN-708 Bug in parsing JSON from Ensemble
and an unreported bug on the show page
> #MAN-703 Error on past program video page

- app/controllers/pages_controller.rb
Caught this unrelated bug when checking another PR.
> Past Programs Video show page

- app/models/form.rb
- app/views/forms/shared/_personal_info.html.erb
- app/views/forms/storage-request/_request-info.html.erb
- config/locales/en.yml
- spec/requests/forms/storage_request_spec.rb
> #MAN-715 Web form needed

- app/dashboards/category_dashboard.rb
- db/migrate/20191009153513_add_fields_to_categories.rb
- db/schema.rb
- spec/factories/categories.rb
- spec/models/category_spec.rb
Added get_help field to model and tests.
Updated description field to text and DescriptionField in dashboard.
> #MAN-444 Add fields to the category entity model

- app/controllers/pages_controller.rb
Honeybadger error: https://app.honeybadger.io/projects/61882/faults/55830083
> Added checks for non-existent collections.

- app/dashboards/building_dashboard.rb
- app/dashboards/collection_dashboard.rb
- app/dashboards/service_dashboard.rb
- app/dashboards/space_dashboard.rb
In any model where the “External Link” field is present, please alphabetize the drop-down menu for ease of finding the desired link.
> #MAN-477 alphabetize drop down menu of external links

- app/views/forms/_all.html.erb
Added link to form on the forms index page
> #MAN-733 Where is the form to request privileged faculty members

- app/controllers/buildings_controller.rb
- spec/controllers/buildings_controller_spec.rb
Redirect to homepage added for buildings index page
> #MAN-726 Remove libraries index route

- app/views/pages/_categories.html.erb
unrendered html was appearing in the description field display.
> #MAN-736 Categories page display

- app/views/forms/purchase-request/_intro.html.erb
> #MAN-722 Purchase Request form

- app/models/form.rb
- app/views/forms/storage-request/_intro.html.erb
- config/locales/en.yml
- spec/requests/forms/storage_request_spec.rb
> #MAN-715 Storage Request Form

- app/dashboards/category_dashboard.rb
- app/dashboards/collection_dashboard.rb
- app/dashboards/page_dashboard.rb
- app/dashboards/policy_dashboard.rb
- app/dashboards/service_dashboard.rb
- app/dashboards/space_dashboard.rb
- app/models/accountability.rb
- app/models/category.rb
- app/models/collection.rb
- app/models/concerns/accountable.rb
- app/models/page.rb
- app/models/policy.rb
- app/models/service.rb
- app/models/space.rb
- config/locales/en.yml
- db/migrate/20191022135457_create_accountability.rb
- db/schema.rb
- spec/models/category_spec.rb
- spec/models/collection_spec.rb
- spec/models/page_spec.rb
- spec/models/policy_spec.rb
- spec/models/service_spec.rb
- spec/models/space_spec.rb
- spec/support/accountable.rb
Creates an accountability model and concern, which is included in
multiple models.
Allows models to have many accounts associsted with them as individual
owners. Adds has many field to relevant dashboards.
> Add Accountability concern to several models

- .circleci/deploy-qa.sh
For clarity, the titular doofus is me.
> Actually commit all the changes you make, doofus

- app/models/exhibition.rb
- app/views/exhibitions/show.html.erb
Add methods and mappings for schema.org
> #MAN-741 Add Structured Data to Exhibitions

- app/models/collection.rb
- app/views/collections/show.html.erb
Add methods and mappings for schema.org
> #MAN-739 Add Structured Data to Collections

- app/models/finding_aid.rb
- app/views/finding_aids/show.html.erb
Add methods and mappings for schema.org
> #MAN-742 Add Structured Data to Finding Aids

- app/models/space.rb
- app/views/spaces/show.html.erb
Add methods and mappings for schema.org
> #MAN-744 Add Structured Data to Spaces

- app/views/forms/partners-borrowing/_intro.html.erb
> #MAN-746 Partners Borrowing Privileges Application form

- app/assets/stylesheets/main.scss
- app/controllers/pages_controller.rb
- app/views/application/_header_navbar.html.erb
- app/views/pages/blockson.html.erb
- app/views/pages/charles.html.erb
- app/views/pages/hsl.html.erb
- app/views/pages/mini-partials/_events.html.erb
- app/views/pages/scrc.html.erb
- app/views/pages/tudsc.html.erb
* Update custom pages to account for missing slugs
* redirect to homepage for pages not found by slug
* add nil checks for all other dependent variables from page controller
> #MAN-629 Decouple code from data

- app/views/pages/videos_search.html.erb
https://app.honeybadger.io/projects/61882/faults/56885940
> Quoted string

- app/views/collections/show.html.erb
- app/views/fields/belongs_to/_form.html.erb
- app/views/fields/photo_field/_form.html.erb
Dashboard edits per ticket
Update show page image to use new dimensions
> #MAN-731 updates to the collection entity admin edit page

- app/views/admin/application/show.html.erb
Update class name check to use underscores on compound names.
> #MAN-732 Finding Aid: Show in website button

- app/models/page.rb
- app/models/policy.rb
- app/models/service.rb
- app/views/pages/orgchart.html.erb
- app/views/pages/publication.html.erb
- app/views/pages/show.html.erb
- app/views/policies/show.html.erb
- app/views/services/show.html.erb
Add structured data to pages, policies, and services.
> #MAN-743 Add structured data to pages an policies and services

- app/dashboards/building_dashboard.rb
- app/views/fields/has_many/_index.html.erb
Added categories to buildings dashboard index view.
> #MAN-730 Building Entity admin interface update to the list view

- app/models/finding_aid.rb
https://app.honeybadger.io/projects/58150/faults/56997479
> Finding aid schema dot org fix

- app/models/exhibition.rb
https://app.honeybadger.io/projects/61882/faults/57256699
> Update fields used for schema.org attributes

- app/models/form.rb
Added Lara Davidson, tuf16063@temple.edu, as recipient.
> #MAN-715_storage_request_form

- app/models/form.rb
- app/views/forms/storage-request/_request-info.html.erb
- spec/requests/forms/storage_request_spec.rb
Added field, will auto-fill if passed from BL.
> MAN-757 Feedback on Storage Request Form

- app/models/form.rb
- app/views/forms/cac-internal/_request-info.html.erb
- config/locales/en.yml
- spec/requests/forms/cac_internal_spec.rb
> #MAN-773 Add field to CAC Internal application form

- app/views/pages/contact/_four.html.erb
> #MAN-771 a link on the Contact Us page

- app/controllers/pages_controller.rb
- app/views/pages/marketing/_slideshow.html.erb
> #MAN-769 Create list of photo captions for website slideshow

- app/models/building.rb
- app/models/category.rb
- app/models/collection.rb
- app/models/finding_aid.rb
- app/models/group.rb
- app/models/person.rb
- app/models/service.rb
- app/models/space.rb
Update models to break association when associated models instances are deleted.
> #MAN-767 Model Dependencies

- app/controllers/buildings_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/policies_controller.rb
- app/controllers/services_controller.rb
- app/controllers/spaces_controller.rb
Previously refactored to use application/categories_list.html.erb.
Removed extraneous code.
> #MAN-719 Refactor navigation_items

- app/controllers/concerns/event_filters.rb
- app/controllers/events_controller.rb
- app/views/events/_events.html.erb
- app/views/events/_facets.html.erb
- config/locales/en.yml
When selecting both a location and type facet, only one facet would be applied.
This allows both to be applied at once.
> #MAN-696 Events Filters

- app/views/application/_header_navbar.html.erb
Applied specific print styles to logo in order for it to print.
> #MAN-781 Printing website pages excludes logo

- app/models/form.rb
Added Jessica Martin (j.martin@temple.edu) to Storage Request form recipients.
> #MAN-782 Storage Request form

- app/controllers/webpages_controller.rb
- app/views/webpages/scrc.html.erb
Update instance variables for consistency
> December Tech-Debt Dependency fixes

- app/dashboards/exhibition_dashboard.rb
- app/views/fields/date_time/_index.html.erb
- config/locales/en.yml
Update admin collection view for Exhibitions.
> #MAN-788 Changes to Exhibition Entity List Display

- app/models/form.rb
- app/views/forms/_all.html.erb
- app/views/forms/group-visit/_personal_info.html.erb
- app/views/forms/group-visit/_request-info.html.erb
- config/locales/en.yml
- spec/requests/forms/group_visit_spec.rb
> #MAN-786 Create form: Group Visit Request Form

- app/controllers/concerns/redirect_logic.rb
- app/dashboards/redirect_dashboard.rb
- config/locales/en.yml
- db/migrate/20200108175223_add_no_message_field_to_redirects.rb
- db/schema.rb
- spec/requests/redirects_spec.rb
Add no_message field to model
Add logic to concern to check for no_message flag and not specify a flash notice if found
Add tests for redirects with flag and without
> #MAN-785 Add option to suppress Update Bookmarks message

- app/dashboards/service_dashboard.rb
- app/views/fields/description_field/_form.html.erb
Updated label for access description and removed requested fields from dashboard form.
> #MAN-794 Changes to Service Entity edit page

- app/dashboards/service_dashboard.rb
- app/views/fields/date_time/_form.html.erb
- app/views/fields/date_time/_index.html.erb
- app/views/fields/has_many/_index.html.erb
- config/locales/en.yml
Updated dashboard index view for Services
> #MAN-795 Changes to Services entity list view

- app/helpers/finding_aids_helper.rb
- spec/features/finding_aids_spec.rb
https://app.honeybadger.io/projects/61882/faults/59518771
> Honeybadger Error

- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_mainmenu.scss
- app/views/application/_header_navbar.html.erb
Add toolbar with requested links
> #MAN-789 Create black bar for "Support the Libraries" and other buttons

- Gemfile.lock
- app/assets/stylesheets/partials/_mainmenu.scss
- app/views/application/_header_navbar.html.erb
Changes position to top of page.
> #MAN-789 Create Black bar update

- app/assets/stylesheets/partials/_mainmenu.scss
- app/views/application/_header_navbar.html.erb
- app/views/fields/has_many/_form.html.erb
Update labels on form to not include full label shown on index view.
> #MAN-7894 Changes to Services Entity edit page

- app/models/concerns/input_cleaner.rb
Accounted for collections created without a subject.
https://app.honeybadger.io/projects/61882/faults/59689972
> HoneyBadger #59689972

- app/views/webpages/tudsc.html.erb
> #MAN-803 LCDSS homepage updates

- app/controllers/persons_controller.rb
- app/helpers/persons_helper.rb
- app/views/persons/_department.html.erb
- app/views/persons/_location.html.erb
- app/views/persons/_staff_type.html.erb
- app/views/persons/_subjects.html.erb
Allow for null values being passed in parameters, and values with no matches. Also allow for filter sections to collapse when no matches are present.
https://app.honeybadger.io/projects/61882/faults/59693509
> Honeybadger: 59693509

- app/controllers/persons_controller.rb
The instance variable change affects the filters working properly so I changed the variable used for the JSON representation and ingest in the catalog.
> FIx for People JSON

- app/controllers/persons_controller.rb
Moved Person.all for JSON directly into the serializer instantiation (code optimization).
> Persons fix -- Redux

- config/locales/en.yml
Fix label for Setup Style field
> #MAN-807 Not all fields coming through on event request email submissions

- app/views/webpages/wpvi.html.erb
> #MAN-4113 WPVI Page correction

- app/controllers/webpages_controller.rb
- app/views/webpages/hsl.html.erb
Added new slug-generated link to HSL homepage.
Slug already added to each env.
> #MAN-824 Add Red Button on HSL homepage for Support the Health Sciences Libraries

- app/models/form.rb
> #MAN-801 Forms: Send confirmation email to submitter

- app/dashboards/highlight_dashboard.rb
- config/locales/en.yml
Added columns to dashboard index view, relabelled Created at to Published at
> #MAN-791 Changes to Highlight Entity List View

- app/dashboards/policy_dashboard.rb
- app/schemas/policy_schema.json
- app/serializers/policy_serializer.rb
- app/views/fields/has_many/_index.html.erb
- config/locales/en.yml
- spec/factories/policies.rb
- spec/models/policy_spec.rb
- spec/serializers/policy_serializer_spec.rb
Updated admin views for policies
This work includes #MAN-793
> #MAN-792 Changes to Policies Entity Edit Screen

- app/views/forms/missing-book/_intro.html.erb
> #MAN-819 Need an edit on a patron form

- app/models/space.rb
Removed no longer needed association from Space model
> Space model cleanup

- app/dashboards/finding_aid_dashboard.rb
- app/views/fields/has_many/_form.html.erb
Added note about Aeon Link requirements.
> #MAN-789 Changes to Finding Aid Edit Screen

- app/controllers/admin/buildings_controller.rb
- app/controllers/admin/categories_controller.rb
- app/controllers/admin/collections_controller.rb
- app/controllers/admin/exhibitions_controller.rb
- app/controllers/admin/finding_aids_controller.rb
- app/controllers/admin/policies_controller.rb
- app/controllers/admin/services_controller.rb
- app/controllers/admin/spaces_controller.rb
- app/controllers/admin/webpages_controller.rb
- app/dashboards/building_dashboard.rb
- app/dashboards/category_dashboard.rb
- app/dashboards/collection_dashboard.rb
- app/dashboards/exhibition_dashboard.rb
- app/dashboards/finding_aid_dashboard.rb
- app/dashboards/policy_dashboard.rb
- app/dashboards/service_dashboard.rb
- app/dashboards/space_dashboard.rb
- app/dashboards/webpage_dashboard.rb
- spec/features/dashboard/building_draft_spec.rb
- spec/features/dashboard/category_draft_spec.rb
- spec/features/dashboard/collection_draft_spec.rb
- spec/features/dashboard/exhibition_draft_spec.rb
- spec/features/dashboard/finding_aid_draft_spec.rb
- spec/features/dashboard/policy_draft_spec.rb
- spec/features/dashboard/service_draft_spec.rb
- spec/features/dashboard/space_draft_spec.rb
- spec/features/dashboard/webpage_draft_spec.rb
Address #1171 MAN-853
Also
- Refactor tests. positive case of feature flag also done in comprehensive create and publish drafts tests.
- Delete all applicable records on test completion.
> Fix inability to create new category records

- spec/services/fuzzy_find/finder_service_spec.rb
Addresses MAN-856
Destroy Person records before running specs
> Destroy Person records before running spec

- app/models/concerns/validators.rb
Update validator to handle blank subject array.
https://app.honeybadger.io/projects/61882/faults/61188873
> Finding Aid Validation

- app/controllers/categories_controller.rb
Update category friendly-find in controller
https://app.honeybadger.io/projects/58150/faults/61261365
> Categories Fix

- app/views/categories/show.html.erb
Add default text to Category show page.
> #MAN-816 Add generic language to categories that don't have a long description

- app/controllers/events_controller.rb
Some type facets were not being applied correctly.
Updated event_type facet handler to parse types from string
> #MAN-863 Event Filters

- app/views/webpages/about.html.erb
- app/views/webpages/research.html.erb
- app/views/webpages/visit.html.erb
Restores landing pages erroneously deleted.
> Landing Page Restoration

- app/dashboards/webpage_dashboard.rb
- app/models/concerns/attachable.rb
- app/models/fileability.rb
- app/models/group.rb
- app/models/webpage.rb
- db/migrate/20200304180056_create_fileability.rb
- db/migrate/20200304180436_remove_file_upload_references.rb
- db/schema.rb
- spec/models/group_spec.rb
- spec/models/webpage_spec.rb
- spec/support/attachable.rb
#MAN-868
Rework file upload polymorphism to allow one to many relationship to models.
> #MAN-868 Allow PDF to be attached more than once

- app/views/admin/application/show.html.erb
Update show in website link to go to the links specified in the external link model.
> Administrate fix link

- app/models/exhibition.rb
- spec/views/exhibitions/show.html.erb_spec.rb
Adds validation for strings formatted in view
> Exhibitions Validations

- app/controllers/groups_controller.rb
- spec/controllers/groups_controller_spec.rb
- swagger/swagger.json
Removes JSON format response for groups.
> Groups JSON fix

- spec/misc/sitemap_generator_spec.rb
> SImplify the test for generating a sitemap

- app/assets/stylesheets/categories.scss
- app/views/application/_categories-mobile-menu.html.erb
- app/views/application/_mobile-menu-items.html.erb
- app/views/categories/show.html.erb
Added mobile sub-navigation to category landing pages.
Added category landing pages to mobile sub-navigation menus.
> #MAN-879 Category headers in Mobile View

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages.scss
- app/views/application/_header_navbar.html.erb
- app/views/webpages/home.html.erb
Add black top bar to intermediate screen sizes.
> #MAN-874 Add black bar to tablet view

- app/controllers/scrc_controller.rb
- config/routes.rb
Logic needed to account for 'collections' in the legacy_path
> Finding Aid Redirects

- db/migrate/20200316141903_add_timestamps_to_redirects.rb
- db/migrate/20200316155112_add_data_to_redirect_timestamps.rb
- db/schema.rb
Add timestamps, populate fields for existing records.
> Adds Timestamps to Redirects

- app/controllers/application_controller.rb
Updated donations slug to use 'categories/support-the-libraries'
> #MAN-878 Donate Slug Update

- public/robots.txt
- Declare existence of a sitemap
- Disallow indexing of admin pages
> Tell search engines about sitemap

- db/migrate/20200325154745_add_uniqueness_to_redirect_index.rb
- db/schema.rb
> Rubocop Update for bundler bump

- google61dc7ab6c8e8a644.html
Added google auth file to root of app
> Google Authorization File

- app/controllers/categories_controller.rb
- app/schemas/category_schema.json
- app/serializers/category_serializer.rb
- config/routes.rb
- spec/serializers/category_serializer_spec.rb
setup serializer for categories
> #MAN-748 Index category description content in Solr and make discoverable in BL

- config/locales/en.yml
> Update Hours Text

- app/controllers/concerns/admin/draftable.rb
- app/views/fields/string/_form.html.erb
Adds note to title field, updates redirect after save to use updated …\slugs.
> #MAN-896 Slug field not updating on Title change

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/partials/_header.scss
- app/controllers/webpages_controller.rb
- app/views/application/_header_navbar.html.erb
Adjust color of alerts and flashes and add Info icon to alerts.
> #MAN-889 Updates to Website homepage - Quarantine

- app/assets/stylesheets/chat.scss.erb
- app/assets/stylesheets/pages.scss
- app/views/layouts/application.html.erb
> #MAN-903 Updates to Website Chat

- app/controllers/webpages_controller.rb
- app/views/webpages/hsl.html.erb
Add remote learner box and link to page.
> #MAN-904 Create "Remote Learning Support" box on HSL mini homepage

- app/views/webpages/tudsc.html.erb
Add staff link to lcdss homepage
> #MAN-906 Add red box to LCDSS mini homepage for staff directory

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages.scss
- app/views/application/_header_navbar.html.erb
- app/views/webpages/home.html.erb
Add Charles Library location to homepage.
> #MAN-907 Add Location box for Charles Library

- app/controllers/application_controller.rb
- app/views/application/_footer.html.erb
- app/views/application/_header-search.html.erb
- app/views/application/_header_navbar.html.erb
- app/views/application/_mobile-nav.html.erb
- app/views/application/_mobile-search.html.erb
- app/views/webpages/home.html.erb
- app/views/webpages/hsl.html.erb
Add redirects to replace the instance variable in the footer and homepage.
This uses a combination of the external links and the internal redirectable types.
New redirects will need to be added for this to be fully functional, and I'l update this description when they are done.
> #MAN-898 Update controller links to use external links

- app/views/events/show.html.erb
Adjust image dimensions on events show page.
> #MAN-921 Images cut-off on events page

- app/views/application/_footer.html.erb
- config/locales/en.yml
adjusted footer links.
Balanced columns due to longer titles wrapping.
> #MAN-920 Update Remove link from Footer

- app/views/layouts/application.html.erb
Update chat links to use redirects.
Redirects entered manually on QA and Prod.
/chat
/sidebar
/hsl/chat
> #MAN-924 update to Chat links on website

- app/controllers/webpages_controller.rb
- app/views/layouts/application.html.erb
- app/views/webpages/contact.html.erb
- app/views/webpages/contact/_one.html.erb
Update redirects on Contact Us page.
> #MAN-918 Update link for See all libraries and locations

- app/controllers/blogs_controller.rb
- app/controllers/buildings_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/concerns/serializable_respond_to.rb
- app/controllers/exhibitions_controller.rb
- app/controllers/finding_aids_controller.rb
- app/controllers/highlights_controller.rb
- app/controllers/persons_controller.rb
- app/controllers/policies_controller.rb
- app/controllers/services_controller.rb
- app/controllers/spaces_controller.rb
- app/controllers/webpages_controller.rb
> Refactor common serializable responds

- app/dashboards/building_dashboard.rb
- app/dashboards/category_dashboard.rb
- app/dashboards/external_link_dashboard.rb
- app/dashboards/file_upload_dashboard.rb
- app/dashboards/person_dashboard.rb
Updated order of fields in dashboards
> #MAN-901 Add Permalink field for each entity

- app/views/collections/show.html.erb
Updates space link on bottom of page.
> #WEB-4690 PJAC page

- Gemfile
- Gemfile.lock
- spec/models/space_spec.rb
FactoryBot 6.0.0 reporting errors not in 4.11.1
Added building to space builds in model spec.
> Fix for FactoryBot update to v 6.0

- app/views/finding_aids/show.html.erb
Updated translation lookup location.
> #MAN-937 Web site button

- app/assets/javascripts/application.js.erb
- app/assets/javascripts/listeners.js
- app/views/application/_header-search.html.erb
- app/views/application/_page-search.html.erb
Add click on search buttons to js for ga
Add listeners for enter key on search forms
> #MAN-935 Add Google Analytics events

- app/views/collections/show.html.erb
Removed extra closing erb tag that was breaking hte link.
> #MAN-935 Web site button

- app/views/events/index.html.erb
- app/views/events/past.html.erb
- config/locales/en.yml
Updated localizations and calls from Events.
> #MAN-937 Events page

- app/assets/javascripts/listeners.js
- app/views/application/_footer.html.erb
updates JS to be less ugly. 
Honeybadger: https://app.honeybadger.io/projects/61880/faults/65428571
> JS Uglifier Error

- config/environments/production.rb
Replace uglifier syntax in production.rb
> Uglifier config update

- .circleci/config.yml
- .circleci/deploy-prod.sh
- .circleci/deploy-stage.sh
- docs/cutting-releases.md
> Change master branch to main in CI/CD

- app/views/events/show.html.erb
Updated translation path for breadcrumbs link.
> #MAN-943 "Breadcrumb" on events page

- app/controllers/library_hours_controller.rb
- app/helpers/library_hours_helper.rb
- app/views/library_hours/_desktop.html.erb
- app/views/library_hours/_mobile.html.erb
- app/views/library_hours/index.html.erb
Break ask a librarian out to its own section on top of list of hours.
> #MAN-937 Hours page updates

- config/locales/en.yml
Update text on event space form.
> #MAN-940 Update Event Booking form

- spec/controllers/blogs_controller_spec.rb
- spec/controllers/buildings_controller_spec.rb
- spec/controllers/collections_controller_spec.rb
- spec/controllers/events_controller_spec.rb
- spec/controllers/exhibitions_controller_spec.rb
- spec/controllers/finding_aids_controller_spec.rb
- spec/controllers/groups_controller_spec.rb
- spec/controllers/highlights_controller_spec.rb
- spec/controllers/persons_controller_spec.rb
- spec/controllers/policies_controller_spec.rb
- spec/controllers/services_controller_spec.rb
- spec/controllers/spaces_controller_spec.rb
- spec/controllers/webpages_controller_spec.rb
- spec/factories/blogs.rb
- spec/serializers/alert_serializer_spec.rb
- spec/serializers/blog_serializer_spec.rb
- spec/serializers/category_serializer_spec.rb
- spec/serializers/collection_serializer_spec.rb
- spec/serializers/exhibition_serializer_spec.rb
- spec/serializers/finding_aid_serializer_spec.rb
- spec/serializers/highlight_serializer_spec.rb
- spec/serializers/policy_serializer_spec.rb
- spec/serializers/service_serializer_spec.rb
- spec/serializers/space_serializer_spec.rb
- spec/serializers/webpage_serializer_spec.rb
- spec/support/serializable_spec.rb
- spec/support/serializer_spec.rb
Refactors tests to one file location for controllers, and one file location for serializers.
> #MAN-300 Refactor tests for JSONAPI schema validation

- app/views/forms/partners-borrowing/_request-info.html.erb
Fixed typo preventing translation.
> #MAN-949 Update Form field names

- app/controllers/webpages_controller.rb
- config/locales/en.yml
Replace virtual ref with charles on homepage todays hours.
> #MAN-951 Update the hours on the homepage

- config/application.rb
> #MAN-954 Anchor link isn't working

- app/controllers/webpages_controller.rb
> #MAN-958 Handle WatchPastPrograms with undefined method `gsub' for nil:NilClass error

- app/assets/stylesheets/partials/_hours.scss
- app/views/library_hours/_desktop.html.erb
- app/views/library_hours/_mobile.html.erb
- config/locales/en.yml
adds hours back in for scrc and blockson.
> #MAN-944 Add text to the hours page

- app/views/buildings/show.html.erb
Remove unnecessary translation call.
> #MAN-960 Link on a webpage call to action button

- app/controllers/admin/external_links_controller.rb
> #MAN-948 Error occurred when attempting to delete external link

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/partials/_header.scss
- app/controllers/webpages_controller.rb
- app/dashboards/alert_dashboard.rb
- app/dashboards/building_dashboard.rb
- app/dashboards/category_dashboard.rb
- app/dashboards/collection_dashboard.rb
- app/dashboards/exhibition_dashboard.rb
- app/dashboards/finding_aid_dashboard.rb
- app/dashboards/policy_dashboard.rb
- app/dashboards/service_dashboard.rb
- app/dashboards/space_dashboard.rb
- app/dashboards/webpage_dashboard.rb
- app/views/application/_header_navbar.html.erb
- app/views/buildings/show.html.erb
- app/views/collections/show.html.erb
- app/views/exhibitions/show.html.erb
- app/views/finding_aids/show.html.erb
- app/views/policies/show.html.erb
- app/views/services/show.html.erb
- app/views/spaces/show.html.erb
- app/views/webpages/show.html.erb
- config/locales/en.yml
- db/migrate/20200731134752_add_covid_fields_to_models.rb
- db/schema.rb
New fields need to be filled in Administrate in order for views to take effect.
Incorporates design layout from MAN-962
> #MAN-966 Add test box to models for COVID alert info

- app/views/categories/show.html.erb
> #MAN-945 Floor plan updates

- app/assets/stylesheets/main.scss
- app/controllers/buildings_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/exhibitions_controller.rb
- app/controllers/finding_aids_controller.rb
- app/controllers/policies_controller.rb
- app/controllers/services_controller.rb
- app/controllers/spaces_controller.rb
- app/controllers/webpages_controller.rb
- app/views/application/_covid_alert.html.erb
- app/views/application/_header_navbar.html.erb
- app/views/buildings/show.html.erb
- app/views/collections/show.html.erb
- app/views/exhibitions/show.html.erb
- app/views/fields/boolean/_form.html.erb
- app/views/finding_aids/show.html.erb
- app/views/policies/show.html.erb
- app/views/services/show.html.erb
- app/views/spaces/show.html.erb
- app/views/webpages/show.html.erb
- config/locales/en.yml
Add help text on For header field.
> #MAN-966 Add text box to models for COVID alert info

- config/locales/en.yml
> #MAN-961 Update buttons on the website homepage

- app/controllers/library_hours_controller.rb
- app/views/library_hours/index.html.erb
> #MAN-956 possible to add "choose a week" to the web calendar

- app/views/events/index.html.erb
> UPDATE: #MAN-975 updates to events page

- app/controllers/events_controller.rb
- app/views/events/_events.html.erb
"Workshop" type events should now show.
> #MAN-980 Workshops not appearing on events page

- app/views/webpages/blockson.html.erb
- app/views/webpages/tudsc.html.erb
https://app.honeybadger.io/projects/61882/faults/67879653
Specify id for link in view.
> ActionController::UrlGenerationError

- yarn.lock
> Yarn 0.10.0

- config/initializers/dashboard_collections.rb
> #MAN-989 Please add new Subject to liaison categories

- app/controllers/webpages_controller.rb
httparty request invalid, so put it into the rescue block, which redirects with message if invalid.
https://app.honeybadger.io/projects/61882/faults/67976985
> Event Video Bug

- app/controllers/events_controller.rb
- config/initializers/dashboard_collections.rb
http://web.qa.tul-infra.page/events?page=1&type=Data#list
> #MAN-997 change in a link on the rdm services webpage

- app/views/events/_events.html.erb
- app/views/events/_featured.html.erb
- app/views/events/_types.html.erb
> #MAN-997 change a link on the RDM Services webpage

- app/controllers/buildings_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/concerns/redirect_logic.rb
- app/controllers/events_controller.rb
- app/controllers/exhibitions_controller.rb
- app/controllers/finding_aids_controller.rb
- app/controllers/groups_controller.rb
- app/controllers/highlights_controller.rb
- app/controllers/policies_controller.rb
- app/controllers/scrc_controller.rb
- app/controllers/services_controller.rb
- app/controllers/spaces_controller.rb
- spec/factories/redirects.rb
- spec/requests/redirects_spec.rb
- spec/requests/services_spec.rb
Removes unless @model from controller call to redirect_or_404
Passes @model to redirect_or_404 for processing
Returns redirection to redirect_path for external and internal paths
Rejects not existent internal paths without redirects
> Redirect Internal Instances

- app/controllers/buildings_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/events_controller.rb
- app/controllers/finding_aids_controller.rb
- app/controllers/services_controller.rb
- app/controllers/webpages_controller.rb
redirect_or_404 breaking out of set instance method before categories could be set. reordered execution.
> #MAN-1000 Category menu not showing on page

- app/controllers/webpages_controller.rb
- app/views/webpages/videos_all.html.erb
- config/locales/en.yml
Account for videos with no tags.
Update name of recent video section.
https://app.honeybadger.io/projects/61882/faults/70332398
> Events Video Feed

- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/partials/_searchbar.scss
- config/locales/en.yml
Update text in config. Update font-sizes
> MAN-1015 Please update the text within the search box

- app/views/library_hours/_desktop.html.erb
- app/views/library_hours/_mobile.html.erb
- config/locales/en.yml
Add 24/7 text to Charles hours section.
> #MAN-1028 Adding something about 24/7 for exams

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_mainmenu.scss
- app/controllers/application_controller.rb
- app/services/sync_service/blogs.rb
- app/services/sync_service/events.rb
- app/views/application/_header_navbar.html.erb
- spec/rails_helper.rb
Reverts tulibraries/manifold#1657
> Revert "MAN-1012 please add drop down menus for the primary navigation"

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_mainmenu.scss
- app/controllers/application_controller.rb
- app/services/sync_service/blogs.rb
- app/services/sync_service/events.rb
- app/views/application/_header_navbar.html.erb
- spec/rails_helper.rb
Add hover menus to main nav, pulling corresponding category items to populate menu.
> #MAN-1012 Please add drop down menus for the primary navigation

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_mainmenu.scss
- app/controllers/application_controller.rb
- app/services/sync_service/blogs.rb
- app/services/sync_service/events.rb
- app/views/application/_header_navbar.html.erb
- spec/rails_helper.rb
Reverts tulibraries/manifold#1664
Not ready for prime time.
> Revert "#MAN-1012 Please add drop down menus for the primary navigation"

- app/assets/javascripts/listeners.js
- app/views/webpages/home.html.erb
Add ids to homepage links. 
Add link ids to listeners.js
> #MAN-1033 Add Google Analytics events to website homepage

- app/views/webpages/wpvi.html.erb
Update playlist embed code with new code to fix broken playlist issues.
> #WEB-4097 Please give these IPs WPVI access

- config/locales/en.yml
> #MAN-1038 Update wording

- app/controllers/events_controller.rb
> #MAN-1040 New events calendar tag

- app/controllers/events_controller.rb
Increased number of exhibits shown.
> #MAN-1042 link past exhibits to Past programs and Exhibits page

- app/controllers/forms_controller.rb
remove file designation on forms controller error redirect
https://app.honeybadger.io/projects/61882/faults/74279599
> Forms controller

- spec/features/dashboard/collection_draft_spec.rb
= Other changes allow this spec to pass.
> MAN-1024 Enable formerly failing Draft Collection Spec

- app/views/webpages/tudsc.html.erb
Add meta tags to LCDSS homepage
> #MAN-1048 DSS mini homepage not appearing Google Search Results

- app/models/form.rb
> #WEB-5894 Instruction form problem

- app/controllers/webpages_controller.rb
- app/views/webpages/blockson.html.erb
- config/locales/en.yml
Add tour links to blockson homepage
> #MAN-1057 Update to Blockson mini homepage

- app/dashboards/webpage_dashboard.rb
- app/views/fields/belongs_to/_form.html.erb
Add blank option to belongs_to field
> Add blank to links list (belongs_to)

- app/controllers/webpages_controller.rb
Only get items if tours present
> Tours controller fix

- app/controllers/webpages_controller.rb
- app/views/webpages/show.html.erb
Controller update checking for presence of tours.
> Fix for Tours

- app/views/fields/description_field/_form_draft.html.erb
Check "all" description fields for actiontext
> Description Field Form Update

- spec/features/dashboard/service_draft_spec.rb
- spec/features/dashboard/service_forms_spec.rb
- Un-skip working specs
- Fix non-passing Service Form Specs
> MAN-1023 Fix Failing Service Forms and Draft Specs

- app/assets/javascripts/administrate/trix-editor-overrides.js
- app/controllers/admin/application_controller.rb
- app/controllers/concerns/admin/draftable.rb
- app/models/alert.rb
- app/models/concerns/input_cleaner.rb
Limit Trix attachments to image files of 1mb or less. Remove alerts from draftability. Remove sanitizing concern for rich text fields.
> #MAN-1029 Limit Saving image/video content to Admin users only

- spec/features/dashboard/collection_draft_spec.rb
> Fix Failing Collection Test

- app/dashboards/webpage_dashboard.rb
- app/models/webpage.rb
- app/views/webpages/_attachments.html.erb
- app/views/webpages/epub.html.erb
- db/migrate/20200827160656_create_structure.rb
- db/migrate/20210318162623_add_epub_to_webpages.rb
- db/schema.rb
> #MAN-1060 Add epub.js epub reader to manifold

- app/serializers/alert_serializer.rb
Add for_header to json.
Note: description field is now an action text model
> #BL-1242 Pull emergency alerts from the website to display in Library Search

- app/javascript/controllers/hello_controller.js
- app/javascript/packs/application.js
remove stimulus related webpack and other config
> Webpack disable

- app/controllers/application_controller.rb
> MegaMenu update

- .gitignore
- app/assets/stylesheets/main.scss
- app/views/webpages/_attachments.html.erb
Adds inline style buttons for downloads of PDF and ePubs
> #MAN-1060 add epub js epub reader to manifold

- spec/features/dashboard/collection_draft_spec.rb
- spec/services/sync_events_spec.rb
> Collections draft

- app/assets/stylesheets/partials/_header.scss
- app/controllers/application_controller.rb
- app/views/application/_header_navbar.html.erb
- app/views/application/_menu-items.html.erb
- app/views/application/_quicklinks.html.erb
Dries up code
Removes parent category form the About menu
> #MAN-1066 implement mega menu drop down

- app/assets/stylesheets/pages.scss
- app/views/webpages/_featured.html.erb
- app/views/webpages/home.html.erb
> #MAN-1063 Implement homepage changes

- app/views/webpages/_virtual-tour.html.erb
actiontext desanitized, no html_safe
> Blockson tours

- Gemfile.lock
- app/assets/stylesheets/pages.scss
- app/views/webpages/_events.html.erb
- app/views/webpages/_featured.html.erb
- app/views/webpages/home.html.erb
Adjust display of news and events
> News & Events

- config/database.yml
Reverts tulibraries/manifold#1859
> Revert "test to show new error page"

- app/views/application/_categories-mobile-menu.html.erb
- config/locales/en.yml
update tours name in config, add html_safe to category name in mobile view
> MAN-1057 Update to Blockson mini homepage

- app/assets/stylesheets/pages.scss
- app/views/application/_header_navbar.html.erb
adjust ql placement in newly ordered about menu. fix outline issue on library events.
> Quicklinks Fix

- app/controllers/webpages_controller.rb
- app/views/webpages/videos_all.html.erb
- config/locales/en.yml
> #MAN-1080 New tagged category for past progrma videos

- app/models/form.rb
- app/views/forms/filming-request/_request-info.html.erb
- config/locales/en.yml
- spec/requests/forms/filming_request_spec.rb
correct typo preventing config strings from being read.
> #MAN-1074 Corrections to the Filming Request form

- app/assets/stylesheets/main.scss
- app/views/webpages/_attachments.html.erb
- app/views/webpages/show.html.erb
> #MAN -1081 Download Epub takes me to an error page

- spec/controllers/application_controller_spec.rb
- Create a Category object, on which slug depends.
> MAN-1078 Fix unintended error

- app/views/webpages/_attachments.html.erb
- app/views/webpages/show.html.erb
- spec/factories/webpages.rb
- spec/features/dashboard/space_show_spec.rb
- spec/features/dashboard/webpage_show_spec.rb
- spec/views/webpages/show.html.erb_spec.rb
Move buttons to the left
Add tests for buttons
> #MAN-1084 update download pdf button text

- app/views/forms/event-space-request/_request-info.html.erb
Restores missing section label
> #MAN-1099 Reinstate Event Space Request Form

- app/assets/javascripts/application.js.erb
- app/assets/javascripts/print.js
- app/assets/stylesheets/print/application.css
- app/views/application/_footer.html.erb
- config/locales/en.yml
Add "print this page" link to bottom of services and policies pages
> #MAN-1102 Create a printer friendly version of webpage

- app/views/webpages/home.html.erb
- config/locales/en.yml
> #MAN-1103 Update call to action buttons 3 and 4

- app/controllers/webpages_controller.rb
Change HSL Remote Learning Support Link
> MAN-1109 Remote Learning Support button not linked

- app/views/persons/specialists_print.html.erb
> #MAN-1107 Create a printer friendly version of the subject specialists page

- app/assets/javascripts/listeners.js
- app/assets/stylesheets/pages.scss
- app/views/webpages/home.html.erb
add scop link to main homepage
> #MAN-1123 Add Center for Scholarly Publishing to locations on homepage

- config/locales/en.yml
> #MAN-1119 Create a mini homepage for the SCOP

- config/locales/en.yml
Test to push through code not appearing in production
> Config Test

- app/controllers/application_controller.rb
- app/views/application/_menu-items.html.erb
Updates to restore checks of Category on Menu Items.
> Application Controller

- app/assets/javascripts/application.js.erb
- app/assets/javascripts/listeners.js
- app/assets/stylesheets/partials/_mainmenu.scss
- app/controllers/admin/menu_groups_controller.rb
- app/controllers/application_controller.rb
- app/dashboards/menu_group_dashboard.rb
- app/helpers/application_helper.rb
- app/models/menu_group.rb
- app/views/application/_header_navbar.html.erb
- config/routes.rb
- db/migrate/20211122204115_create_menu_groups.rb
- db/migrate/20211129222602_add_menu_id_to_categories.rb
- db/schema.rb
- lib/tasks/menu_seed.rake
- spec/factories/menu_groups.rb
- spec/helpers/application_helper_spec.rb
- spec/models/menu_group_spec.rb
rake task deletions commented until we can test on qa
easier that recreating if needed to be done more than once
will amend for production when qa satisfied
> #MAN-1141 top level categories

- Gemfile
- Gemfile.lock
> #MAN-1142 Update Image Processing

- app/assets/stylesheets/pages.scss
> #MAN-1138 Remove RefWorks link on homepage

- package.json
- yarn.lock
update webpacker to resolve dependency issues
> Webpacker Update

- app/views/application/_footer.html.erb
- app/views/application/_quicklinks.html.erb
> #MAN-1144 Remove Refworks link from the quick links

- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
- app/views/application/_header_navbar.html.erb
- config/routes.rb
- lib/tasks/menu_seed.rake
- spec/helpers/application_helper_spec.rb
Re-enables top-level categories for menu navigation
> Revert menus

- app/assets/javascripts/listeners.js
- app/views/application/_header-search.html.erb
- app/views/application/_mobile-search.html.erb
- app/views/application/_page-search.html.erb
- app/views/webpages/home.html.erb
update search to go directly to Primo
> Temporary Search

- app/assets/javascripts/listeners.js
- app/views/application/_header-search.html.erb
- app/views/application/_mobile-search.html.erb
- app/views/application/_page-search.html.erb
- app/views/webpages/home.html.erb
Reverts tulibraries/manifold#2206
> Revert "Restore search functionality and homepage links."

- config/routes.rb
Restores redirect to scrc reading room.
> SCRC Reading Room

- app/assets/stylesheets/chat.scss.erb
- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/partials/_footer.scss
- app/views/application/_footer.html.erb
- app/views/webpages/_events.html.erb
- app/views/webpages/_featured.html.erb
- app/views/webpages/home.html.erb
Updates for mobile view of homepage only
> Man 1172 styling change for custom pages and throughout the site

- app/assets/stylesheets/mini-pages.scss
- app/assets/stylesheets/partials/_footer.scss
- app/assets/stylesheets/partials/_header.scss
- app/assets/stylesheets/partials/_searchbar.scss
- app/controllers/webpages_controller.rb
- app/views/application/_footer.html.erb
- app/views/webpages/hsl.html.erb
@sensei100 header alerts are now set in the application controller, just cleaning up. Still no effect on library search as the JSON is set in the alerts controller. Header alerts are used for display purposes only within manifold.
> HSL mini-page, desktop only

- app/models/finding_aid.rb
MAN-1179: JSON endpoint updates
> MAN-1179-add-helper-text-to-finding-aid-form

- app/controllers/finding_aids_controller.rb
- app/models/finding_aid.rb
Adds scopes to only filter on existing values
> MAN-1179 finding aids

- Gemfile
- Gemfile.lock
- app/controllers/finding_aids_controller.rb
- app/models/finding_aid.rb
- spec/models/finding_aid_spec.rb
- spec/rails_helper.rb
Requires the description field which breaks the JSON feed if left blank.
> FindingAids update

- app/assets/javascripts/listeners.js
- app/views/webpages/hsl.html.erb
- config/locales/en.yml
Also add to analytics event listeners.
> MAN-1185 add link to HSL page

- Gemfile
- Gemfile.lock
> Pin selenium-webdriver to 4.2.1.

- app/views/webpages/videos_all.html.erb
> MAN-1197 test script from panopto to website for past events

- app/helpers/event_helper.rb
- app/models/event.rb
- app/views/fields/date_time/_form.html.erb
- spec/models/event_spec.rb
- spec/services/sync_events_spec.rb
Removes direct editing of event dates, which caused homepage errors when left empty
> Events Update

- app/controllers/webpages_controller.rb
add debug lines to controller for testing 3rd party api issue
> Video Debug

- app/views/webpages/contact.html.erb
updates size and id to live widget
> Chat widget update

- app/assets/stylesheets/events.scss
update style for homepage event links
> CSS hotfix

- .circleci/config.yml
Reverts tulibraries/manifold#2661
> Revert "Try adding user key"

- app/controllers/buildings_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/exhibitions_controller.rb
- app/controllers/finding_aids_controller.rb
- app/controllers/policies_controller.rb
- app/controllers/services_controller.rb
- app/controllers/spaces_controller.rb
Reverts tulibraries/manifold#2674
> Revert "restore alert variable to controllers"

- app/views/buildings/show.html.erb
- app/views/categories/show.html.erb
- app/views/collections/show.html.erb
- app/views/exhibitions/show.html.erb
- app/views/finding_aids/show.html.erb
- app/views/policies/show.html.erb
- app/views/services/show.html.erb
- app/views/spaces/show.html.erb
- app/views/webpages/show.html.erb
Reverts tulibraries/manifold#2673
> Revert "restore partial call in model show pages"

- app/assets/stylesheets/main.scss
- app/controllers/buildings_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/collections_controller.rb
- app/controllers/exhibitions_controller.rb
- app/controllers/finding_aids_controller.rb
- app/controllers/policies_controller.rb
- app/controllers/services_controller.rb
- app/controllers/spaces_controller.rb
- app/views/application/_secondary_covid_alert.html.erb
- app/views/buildings/show.html.erb
- app/views/categories/show.html.erb
- app/views/collections/show.html.erb
- app/views/exhibitions/show.html.erb
- app/views/finding_aids/show.html.erb
- app/views/layouts/application.html.erb
- app/views/policies/show.html.erb
- app/views/services/show.html.erb
- app/views/spaces/show.html.erb
- app/views/webpages/show.html.erb
Finishes covid alert restoration on secondary pages
> Restore secondary covid alerts

- app/controllers/forms_controller.rb
disable saving encrypted attributes to db
> remove form persistence

- app/views/forms/filming-request/_intro.html.erb
> MAN-1237 update request for filming form

- app/javascript/src/administrate-trix.js
> MAN-1236 headers in manifold wysiwyg editor

- app/serializers/concerns/description_serializable.rb
> MAN-1246 create static endpoint for finding aid serialization

- Gemfile.lock
Reverts tulibraries/manifold#2829
> Revert "Revert "Bump pg from 1.5.2 to 1.5.3""

- app/assets/stylesheets/persons.scss
- app/views/persons/index.html.erb
corrects additional bug found in testing
> MAN-1279 department listing in staff directory

- app/serializers/event_serializer.rb
Typo was causing 500 error when no external city provided
> Events Serializer

- .docker/app/Dockerfile
- Keep kubernetes deployment configuration up to date
> Update package dependencies in Docker

- app/controllers/webpages_controller.rb
Used created_at rather than updated_at. Typo in the commit message...
> MAN-1301 recent blog posts change data point

- app/controllers/admin/groups_controller.rb
- app/dashboards/group_dashboard.rb
- app/models/group.rb
- app/models/service_group.rb
Admin controller was overridden
Cleaned up unused code from previous incarnation(s) of this model
> Man-1313 new groups wont save

- app/controllers/webpages_controller.rb
- spec/rails_helper.rb
Cleans up with truncation after suite so each run starts clean.
> Dbcleaner transactions

- app/models/form.rb
- app/models/group.rb
- spec/factories/form_infos.rb
- spec/factories/forms.rb
- spec/factories/groups.rb
- spec/models/exhibition_spec.rb
- spec/models/form_info_spec.rb
- spec/models/form_spec.rb
- spec/models/group_spec.rb
- Adds tests for form and form_info models
- Removes pending line from exhibitions because it does have tests
- Removes unused methods from group model
- Refactors validation tests for groups
> DEVO-873 Updates pending specs for some  models

- app/components/google/etextbooks_component.html.erb
Adding the data formatting needed for the etextbook table display
> MAN-1344 Etextbooks data formatting

- app/controllers/forms_controller.rb
- app/dashboards/form_info_dashboard.rb
- app/models/form_info.rb
- app/views/forms/index.html.erb
- config/initializers/dashboard_collections.rb
- db/migrate/20231116200354_add_grouping_field_to_form_info.rb
- db/schema.rb
- spec/factories/form_infos.rb
- spec/features/forms_spec.rb
- spec/models/form_info_spec.rb
Makes forms index page dynamic.
> MAN-1355 forms page text update

- app/assets/stylesheets/main.scss
- app/javascript/application.js
Update fontawesome to include js
> MAN-1380 address performance issues found in speed tests

- public/robots.txt
Adds Googlebot only as a test for new k8s environment
> MAN-1402 re-crawl library.temple.edu

- .docker/app/Dockerfile
Adds Jpeg support. Addresses honeybadger error: https://app.honeybadger.io/projects/61882/faults/108822585
> Imagemagick Dev tools

- app/controllers/persons_controller.rb
- app/helpers/persons_helper.rb
- app/models/person.rb
- app/views/persons/_persons_list.html.erb
- app/views/persons/index.html.erb
- app/views/persons/specialists_print.html.erb
- config/locales/en.yml
- spec/factories/persons.rb
- spec/helpers/persons_helper_spec.rb
- spec/requests/people_spec.rb
Makes subject specialist link dynamic to which, if any, dept is being displayed
Also updates print views for these specialists lists
> MAN-1365 limit to subject specialists only feature

- app/models/form.rb
- app/views/forms/event-space-request/_request-info.html.erb
- config/locales/en.yml
- spec/requests/forms/event_space_request_spec.rb
Add back field requested to be removed and rename and reposition it
> MAN-1411 update event space request form

- package.json
- yarn.lock
Addresses:  Prototype Pollution [Low Severity][https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795] in minimist@0.0.10
> Update minimist to 0.2.4

- app/services/google/sheets_connector.rb
https://app.honeybadger.io/projects/61882/faults/114685732
Google::Apis::RateLimitError: Rate limit exceeded
> Google API exponential backoff

- config/locales/en.yml
- spec/helpers/event_helper_spec.rb
Waiting for response whether to update Events index page's title
> MAN-1453 Update Events label on Library home page

- app/assets/stylesheets/homepage-slideshows.scss
- app/views/webpages/_dig-cols.html.erb
Corrects issue of slideshow controls overlapping link text below them
> MAN-1461 investigate-adding-slideshow-functionality-to-homepage-highlights-sections

- app/views/webpages/home.html.erb
- config/locales/en.yml
- spec/system/homepage_digcol_collection.rb
Additional update to move section titles to config
> Fix for highlights sections on homepage

- Documentation/Ruby-CVE-2025-43857
- Documentation/essential_packages.txt
> Net imap documentation

- app/dashboards/external_link_dashboard.rb
- app/dashboards/file_upload_dashboard.rb
- app/dashboards/highlight_dashboard.rb
- app/helpers/application_helper.rb
- app/models/highlight.rb
- app/services/sync_service/events.rb
- app/views/application/_footer.html.erb
- app/views/webpages/_dig-cols.html.erb
- app/views/webpages/_events.html.erb
- app/views/webpages/_featured.html.erb
- app/views/webpages/_reports.html.erb
- app/views/webpages/home.html.erb
- db/migrate/20250520212422_add_alt_text_to_highlights.rb
- db/migrate/20250521131631_add_alt_text_external_links.rb
- db/migrate/20250521135706_add_alt_text_to_file_uploads.rb
- db/schema.rb
- spec/services/sync_events_spec.rb
This portion of the work focuses on alt tags for images but also includes a couple homepage issues, captions, admin login, aaria-labels
> Accessibility updates 05 20 25
