tulibraries/manifold

app/dashboards/account_dashboard.rb, app/models/account.rb
- Had to remove `NameError in Admin::AccountsController#destroy
uninitialized constant Account::OauthCredential`
because we were getting
`NameError in Admin::AccountsController#destroy uninitialized constant Account::OauthCredential`
Besides, this was only found in one example of an Google Oauth2
implementation.
=> Clean up account edit form and fix account deletion

Gemfile, Gemfile.lock, app/models/account.rb, app/models/building.rb, app/models/group.rb, app/models/person.rb, app/models/space.rb, spec/models/building_spec.rb
Issue #LWR-129 - Strip out leading or trailing spaces so that email address can be validated.
=> Use auto_strip_attributes to strip spaces

spec/dashboards/building_dashboard_spec.rb, spec/dashboards/person_dashboard_spec.rb, spec/monkey_patches/administrate_field_base_spec.rb
- Fixed broken specs that merge induced.  Errors were
An error occurred while loading the committed files. Must use 
`Rspec.describe` block
`
=> Fixes broken specs from monkey patch merge

Dockerfile, docker-compose.yml, docker-readme.md
- Docker usage in docker-read.md
- Uses local directory as shared mount so it works as Vagrant would, 
allowing live updates to code.
=> Add docker capability

README.md, app/helpers/application_helper.rb, app/views/devise/sessions/new.html.erb
Currently we are hardcoding the Redirect URI in code that's in source control. This should take care of that problem code by specifying the URI as an environment variable. If not specified, URI defaults to `http://localhost:3000/accounts/auth/google_oauth2`.
=> Specify OAuth Redirection URI in ENV

app/models/building.rb, app/models/space.rb, spec/models/building_spec.rb, spec/models/space_spec.rb
Restores required description field validation we had to take out when required wasn't working with text fields.
=> Re-enable description validation

Gemfile, Gemfile.lock, app/services/fuzzy_finder_service.rb, spec/services/fuzzy_finder_service_spec.rb
Uses the FuzzyMatch gem under the hood, which uses the dice coefficient and  levenshtein distance algorithms.
Will help to identify records in our database with exterbal systems, like blogs, events, etc.
For example, blog feeds include a person's name as the Author, but spelling may vary slighty (Joe vs Joeseph, missing middle names, etc.). This will allow us to connect programmatically imported records to existing DB records and people.
=> Adds a FuzzyFinderService that can be used to add find similar strings in attributes for a given model. 

app/services/fuzzy_find/building.rb, app/services/fuzzy_find/event.rb, app/services/fuzzy_find/finder_service.rb, app/services/fuzzy_find/person.rb, app/services/fuzzy_find/space.rb, spec/services/fuzzy_find/building_spec.rb, spec/services/fuzzy_find/event_spec.rb, spec/services/fuzzy_find/finder_service_spec.rb, spec/services/fuzzy_find/person_spec.rb, spec/services/fuzzy_find/space_spec.rb
Wraps the models likely to need to be found by fuzzy matches in
convenience methods to make them easier to use.
=> Add convenience wrappers for fuzzy service

db/migrate/20181025181642_remove_phone_and_email_from_groups.rb, db/schema.rb
- Removing these fields caused deployment to fail. Restoring
just the fields. Leaving the back-end code in place.
=> Restore phone and email fields in groups

spec/controllers/groups_controller_spec.rb, spec/controllers/persons_controller_spec.rb, spec/controllers/spaces_controller_spec.rb, spec/factories/groups.rb, spec/factories/persons.rb, spec/factories/spaces.rb, spec/models/group_spec.rb, spec/models/space_spec.rb, spec/views/groups/show.html.erb_spec.rb, spec/views/persons/show.html.erb_spec.rb
- Move creation of associated objects in Group, Space, and Person
from spec into factory where it belongs. Removes redundant setup
of these dependencies from all of the tests
- Make building association creation in space the default condition
so we don't have to have :space_with_building in all of the specs.
In order to test for missing building in space, we set
space.buidling to nil.
=> Refactor group, spaces, and person factories

app/assets/stylesheets/partials/_card-rows.scss, app/controllers/pages_controller.rb, app/dashboards/highlight_dashboard.rb, app/views/pages/home.html.erb
This adds the highlights, previously modelled and dashboarded, to the main homepage.
The highlights did not exist when the current homepage was created, so they were mocked up with static data.
The date and time fields are throwing errors if left blank and need to be looked at in future to prevent this.
=> Adding custom highlights to view page (main homepage only)

app/assets/stylesheets/partials/_footer.scss, app/views/application/_footer.html.erb
This is for ease of navigation to stake holders checking the site, so they don't have to type anything into the address bar to browse the main sections of the site.
=> Turned column heading in footer into links to model index pages.

app/dashboards/service_dashboard.rb, app/fields/multi_select_field.rb, app/models/service.rb, app/views/fields/multi_select_field/_form.html.erb, spec/models/service_spec.rb
Services were not able to be saved as intended audience was not being permitted as a param, and thus was always nil.
=> Fix intended audience being rejected as not permitted

app/views/fields/multi_select_field/_show.html.erb
Administrate show page for person was erroring when no subject specialties were assigned to a person.
=> Administrate show page errors

app/assets/stylesheets/application.scss, app/dashboards/highlight_dashboard.rb, app/views/highlights/show.html.erb, app/views/pages/home.html.erb, db/migrate/20181205150746_remove_time_and_date_fields_from_highlights.rb, db/schema.rb, spec/factories/highlights.rb, spec/views/highlights/show.html.erb_spec.rb
#MAN-27
Create four news and highlights slots where Sara and Kaitlyn can manually add news and highlight items. There should be a link, an image and text. This is similar to the manual spots you created on the TUpress site.
These will likely need to be stored locally on the server, as opposed to being streamed in from WordPress, LibGuides, etc.
*****************
- Updated fields for highlights and adjusted show page to display on site rather redirect to external or other internal url.
- Cleaned up tests and rubocop
=> MAN-27 News and highlights section

app/assets/stylesheets/persons.scss, app/views/persons/show.html.erb
MAN-126 Enlarge_Schedule_an_appointment_button
On the person entity page, please make the "Schedule an appointment" button slightly larger and more prominent. Make the background red and the text white and slightly bolder.
Comments:
G. Christopher Doyle added a comment - 27/Nov/18 4:23 PM
Rachel and I had agreed to drop the red background as the button is not applied to each person on a page listing and the red really pulls the eye in different directions depending on which entries have the button or not, creating more of a jumbled display rather than a nice, neat and even display as seen with the toned down buttons. They could be a bit larger if necessary, but the change in color was purposeful.
Cynthia Schwarz added a comment - 1 week ago
I agree that this looks good when looking at a …
=> Enlarged font on button.

app/controllers/admin/events_controller.rb
- Addresses Issue: MAN-130
- Cannot update events when we set sort ordering on start date when we
pass the :order and :direction parameters.
- Solution Reference:
[https://github.com/thoughtbot/administrate/issues/442#issuecomment-439209910]
=> Add workaround that prevents updating events

app/views/application/_footer.html.erb
#MAN-140
Can you make the "Donate to the libraries" button span a wider area so that it doesn't wrap when you shrink the screen.
**********************************
Adjusted non-breaking of text in Donate link down to lowest supported resolution. It will line break if you reduce the browser width to below the smallest device size, but that will never happen on a device, and if a browser is that small the site is unusable anyway.
=> Prevent word-breaks in donate button

app/assets/stylesheets/services.scss, app/views/services/show.html.erb, db/schema.rb, spec/views/persons/index.html.erb_spec.rb
Can you apply the maximum width to the service entity page, similar to what you did with the home page?
when I look at it on my screen, the white space is added between the columns, not on the edges
*****************************************
- Adjusted side boxes to float toward center, and allowed word wrap on bulleted items in related categories list.
- Updated test to check for new page title
=> #MAN-152 updates to finish ticket

app/assets/stylesheets/partials/_footer.scss, app/controllers/application_controller.rb, app/dashboards/building_dashboard.rb, app/dashboards/collection_dashboard.rb, app/dashboards/group_dashboard.rb, app/dashboards/service_dashboard.rb, app/views/application/_footer.html.erb, db/migrate/20190109153034_add_footer_link_checkboxes.rb, db/schema.rb, spec/views/persons/index.html.erb_spec.rb
#MAN-28
Add a field to the entity model for buildings, services, groups and collections labeled "Add to footer".
Field should be a check box.
Field is optional.
Field is an admin-only change.
The "Add to footer" checkbox will designate items that appear in the footer.
************************************
- Added add_to_footer checkbox to four footer models
- updated application controller and footer partial to only pull checked instances.
- rubocop, test fixes
=> #MAN-28 Entities Add To Footer Link

app/assets/stylesheets/buildings.scss, app/dashboards/group_dashboard.rb, app/models/building.rb, app/models/group.rb, app/views/buildings/index.html.erb, app/views/buildings/show.html.erb, lib/uploads.rb
#MAN-202 
Similar to what we did on the main homepage, can you remove the space between the building entities on the index page and instead have more white space on the outside of the three columns.
- Changed rows of three to rows of four in order to minimize space betw…een images when window stretches.
- Also optimized calls to and display of images for index and show pages.
=> #MAN-202 Remove space between entities

app/dashboards/group_dashboard.rb, app/models/group.rb, db/migrate/20190128201026_add_parent_group_id_to_groups.rb, db/schema.rb, spec/models/group_spec.rb
#MAN-107 Create a "home department" group in Person Entity
Create a new field for "home department". This field will be a related group and will be the person's home department. The "Groups" field will be used to list any other groups that this person belongs to that are secondary to their home department.
The contact information that displays on the person's page will be pulled from the 'Home department' related space information.
********************************************
Added the ability to add another group to a particular group, which would then be the parent group and the cild groups can be parsed out in the display(s).
=> #MAN-107 Create a "home department" group in Person Entity

app/models/building.rb, app/models/space.rb, spec/models/building_spec.rb, spec/models/space_spec.rb
#MAN-22 
The building model validates the presence of Email and Hours, but the Dashboard form does not indicate they should are required with an asterisk.
Space entity requiring email and phone for validation, even though these fields are optional.
******************************************
Removed Email from Building required status. Hours must have been previously removed.
Removed validations for optional email and phone in Spaces
=> #MAN-22 Hours and Email not marked as required in Building form, but are required by validations

config/tinymce.yml
#MAN-209 Add lists and tables to Tinymce editors
We need a way to create bulleted/numbered lists and tables. This is a big one – a lot of the content we've been working on contains lists and tabular data. In the writing for the web workshop, creating lists was one strategy I suggested for keeping content succinct and making it easy for users to scan the page. Tables are important for things like borrowing rules. I realize we don't want people using tables to format content on the page, but we can deal with that by... telling them not to.
Enabled lists and tables in Tinymce
=> #MAN-209 Add lists and tables to Tinymce editors

config/application.rb, config/tinymce.yml
#MAN-222
I am using the Insert -> table feature in the tinymce editor in the services entity. When I go to the view page, the table does not render as a table.
*****************
This only happened on Description fields. Description fields are being sanitized in the model and this was stripping out some html tags, so I had to specify all allowed tags in config and tables now show up.
Add allowed html tags to config.
Add code button to tinymce editor
=> #MAN-222 Tables not displaying

app/views/application/_footer.html.erb
#MAN-206 Responsive footer - Overlapping text
On responsive pages, the text in the footer is overlapping in a weird way.
*****************************************
Corrected overlapping text.
=> #MAN-206 Responsive footer - Overlapping text

Gemfile, Gemfile.lock, app/assets/stylesheets/events.scss, app/assets/stylesheets/partials/_pagination.scss, app/assets/stylesheets/partials/_vars.scss, app/controllers/events_controller.rb, app/dashboards/event_dashboard.rb, app/dashboards/exhibition_dashboard.rb, app/models/event.rb, app/services/sync_service/events.rb, app/views/events/_events.html.erb, app/views/events/_exhibitions.html.erb, app/views/events/_facets.html.erb, app/views/events/index.html.erb, app/views/events/show.html.erb, config/routes.rb, db/migrate/20190207145221_add_fields_to_events.rb, db/schema.rb, spec/factories/events.rb
#MAN-208
This design was reviewed with communications staff and agreed upon
***************************************
Add Kaminari for pagination (chose this gem for compatibility with Administrate)
Add event_type field to model since tags is not where Event Type comes from in the xml feed
Update event sync service to pull type field and map to event_type
Add promoted to events checkbox to exhibition model to pull only those approved to the events page
Serialized tags and types with methods in model
Added methods to model to call image variants from view
Updated routes to remove beyondthepage reference and revert
=> #MAN-208 Code event/exhibit index page

Gemfile.lock
Bundler 2.0 is now the default when ruby 2.5.1 is installed. This upgrades ugrade to Bundler 2.0.
@skng5 and @cdoyle-temple This will requre you to manually reinstall bundler to get bundler 2.0 on your local environments.
=> Use Bundler 2.0

config/environments/development.rb, config/environments/production.rb
Rails needs to know the fqdn to set a root_url, so we need to set that in a config via an env variable.
=> Use env var for FQDN in production

app/services/sync_service/events.rb
#MAN-246 
The events sync service writes default values from en.yml when a field has no value in the xml feed. These should be removed from the service and null values dealt with in the views.
****************
Removed setting translations for empty fields in the sync service and substituted nil.
=> #MAN-246 Remove translation defaults on events sync service

app/services/sync_service/events.rb, spec/factories/buildings.rb, spec/fixtures/files/fuzzy_events_internal.xml, spec/services/fuzzy_find/finder_service_spec.rb, spec/services/sync_events_spec.rb
Add the event address into the matching algorithm to lower the chance of
false positives in buidling matches.
=> Use event address when matching buildings

app/controllers/images_controller.rb, config/routes.rb, spec/controllers/images_controller_spec.rb, spec/factories/collections.rb, spec/factories/exhibitions.rb, spec/rails_helper.rb, spec/routing/buildings_routing_spec.rb, spec/routing/collections_routing_spec.rb, spec/routing/events_routing_spec.rb, spec/routing/exhibitions_routing_spec.rb, spec/routing/person_routing_spec.rb, spec/support/image_route_concerns.rb
Allows thumbnail, medium, and large images for entites with images to be
accessed via a standarised route. The route redirects to the appropriate
active_storage route, but we don't have to embed those urls into JSON
representations of the data.
Adds route and controller teets.
=> Add restish route support for images via concern

app/controllers/admin/application_controller.rb, config/initializers/paper_trail.rb, spec/controllers/admin/events_controller_spec.rb
Also switch to a before_action filter instead of overriding edit.
Remove initializers to serialize as JSON.
=> Use reify instead of custom calls.

app/views/application/_header_navbar.html.erb, config/routes.rb
update routes and main menu to use path helpers. this is to avoid a Devise error when calling controller methods as paths in the views.
=> Fix for Devise and controller paths error

app/controllers/admin/blogs_controller.rb, app/models/blog.rb, app/services/sync_service/blogs.rb, lib/tasks/blogs_sync.rake, spec/controllers/admin/blogs_controller_spec.rb
Additionally, refactors the service a bit to reduce the number of DB calls and leverage the services built in ability to sync all blogs.
Adds some tests for the sync and sync_all methods on the Admin::BlogsController.
Additionally, updates Blogs model to destroy dependent blogposts when the Blog is deleted.
=> Fixes Blog Sync not working from the Admin dashboard

app/assets/javascripts/application.js, app/controllers/services_controller.rb, app/views/services/_all_services.html.erb, app/views/services/_mobile_menu.html.erb, app/views/services/_mobile_services.html.erb, config/routes.rb
Updated secondary menu per ticket.
This should act as the navigation for all models displaying left-side categories but will need to included in each model's templates.
This can only be seen on the Services model, as of now.
(Also re-ordered administrate menu items in routes.rb to be alphabetical)
=> #MAN-310 Revise Responsive menus

app/assets/stylesheets/partials/_hours.scss, app/controllers/library_hours_controller.rb, app/models/building.rb, app/models/concerns/has_hours.rb, app/models/space.rb, app/views/admin/categories/show.html.erb, app/views/admin/library_hours/index.html.erb, app/views/buildings/_show_hours.html.erb, app/views/buildings/show.html.erb, app/views/library_hours/show.html.erb, config/application.rb
Please create the ability to display relevant hours in both the building and space entities. The design for the building page is in MAN‌-344 . Jackie Sipes is still working on the wireframe for the space entity display. However, it should look the same as the building display page.
This should be a widget/helper that can be dropped into any entity display page that has hours tracked in the spreadsheet.
****************************************
Add hours logic to to concern, has_hours
create model partial for hours display, currently building only
Extended formatting not included in this ticket as it will be applied through the model's views.
=> #Man-346 hours display for buildings and spaces

app/models/category.rb, spec/models/category_spec.rb
Adds a `limit_to` param  to Category#items to limit the items
returned to the classes indict`aed in the array.
Adds a Category#child_categories convenience method to just get the
child categories of a category.
=> Parameterize Category#items

app/assets/stylesheets/partials/_searchbar.scss
If you stretch from mobile to tablet with the search open, the search box then displays twice. Can you remove the search box from the header and instead have the mobile search icon.
Adjusted overlap from bootstrap breakpoints to hide searchbar on page when searchbar in header becomes visible.
=> #MAN-358 Tablet view - remove the search box from the header

app/controllers/spaces_controller.rb, spec/controllers/spaces_controller_spec.rb
Issue: #MAN-379
- Provides all spaces for Solr harvest.
- JSON response to index json request.
- Raises 404 if an html request is made to the index action.
=> Shows a spaces index for json request only

app/controllers/pages_controller.rb, app/models/category.rb, app/views/admin/application/show.html.erb, app/views/admin/categories/show.html.erb, app/views/pages/_categories.html.erb
- Removed serialization from Research Services page as it belongs in the index method of the page controller
- Updated url method to provide link in cases where first item in category is an external link
- Corrected malformed html in override of administrate's application show page
- Removed "show in website" button from overridden categories admin show page (they don't have their own pages)
- Updated links in category show page to use custom helper override category_path (for entities this returned either the link to the entity or the custom_url of a category AND now also will return the link from an external link if that is the first item in the category)
=> #MAN-286 Code Research Services Page

app/views/application/_mobile-menu-items.html.erb, app/views/buildings/_categories.html.erb, app/views/buildings/_mobile_categories.html.erb, app/views/pages/_items.html.erb, app/views/services/_all_services.erb, app/views/spaces/_all_spaces.html.erb
Show page errors as it can't find external_link_path.
Updated call to entity_path for category items using custom category_url in routes.rb.
=> Error on linode when external link added to a space

app/views/pages/_categories.html.erb
The word "internal" appears in each of the category descriptions even though that word is not part of the description.
****************
Removed irrelevant text
=> #MAN-388 "Internal" appears in category description 

app/models/category.rb, config/routes.rb, spec/factories/categories.rb, spec/helpers/route_helpers_spec.rb, spec/models/category_spec.rb
Additionally, cleans up category url to ignore external_link items when generating a route.
=> Adds external_link_url route helper

app/views/buildings/_categories.html.erb, app/views/services/_all_services.erb
Please remove the word "menu" from the secondary (category) menus on the left hand display.
This applies to both responsive and desktop view.
****************************
Removed the word 'menu' from side-menu titles. This only applied to buildings and services as they used the old style when they were coded.
=> #MAN-401 Remove "menu" from the category menus

app/assets/stylesheets/application.scss, app/assets/stylesheets/forms.scss, app/views/forms/_all.html.erb, app/views/forms/index.html.erb, app/views/forms/recall-book/_intro.html.erb
Removed old styles. Kept forms to 9 columns, 3 empty to the right.
=> #MAN-403 Bring forms pages up to current design standards

app/controllers/concerns/event_filters.rb
Added logic to filter helper where locations are not supplied from old events in Drupal to ignore the nils.
=> Events feed from Drupal

app/assets/stylesheets/events.scss, app/assets/stylesheets/persons.scss, app/assets/stylesheets/services.scss
1. Events index page - remove grey background from filtering
2. On events index, staff directory and finding aids index, highlight filters with a green background and white text similar to how menu items are highlighted in the left hand nav menus. 
3. For all index lists (staff directory, finding aids, events), highlight selected filter with green background as we do with the left hand nav. Also keep the X.
*************************
Removed grey backing on left-side of events index, staff directory and finding aids indexes, Replaced white active selection color with green and orresponding whte text. X deslect link also changed to white.
=> MAN-434 left hand menu styling

app/views/library_hours/index.html.erb
I have just one request: can you make the grey behind “library hours” extend to the width of the screen (on desktop)? That’s all!
************************
Adjusted grey bar to 100% outside of container.
=> #MAN-445 Update Library Hours desktop and mobile

app/controllers/admin/pages_controller.rb
- Fixes an error thrown when attempting to visit pages administrate
index view after the first page.  There is a conflict between
the page object and pagination pages in the administrate params
passed to the controller order method.  To avoid this problem,
we will bypass the ability to order pages in the administrate
index view.
=> Don't display ordered pages in administrate

.travis/deploy-prod.sh, .travis/deploy-stage.sh
Unlike, travis doesn't atm support manual approval for the prod deploy, but it at least waits until stage deploys /shrug
=> fixing travis deploy scripts for stage + prod to use master, diff git dirs.

app/views/pages/tudsc.html.erb
Please link the blog posts to the individual post on the home blog (sites.temple.edu/dsc/…), not a show page within the CMS.
Please link the “View all” in the blogs to the homepage of the blog in sites (sites.temple.edu/dsc), not the show page in the CMS
=> #MAN-439 Update blog links on DSC homepage

app/models/concerns/imageable.rb
- Addresses Issue #MAN-460
- Fixes error thrown if image dimensions match show image dimensions,
If the dimensions match, mogrify optimization throws error due to
failure to find expected temporary file to mogrify in /tmp directory
=> MAN-460 Don't process show image if size matches show image dimensions

app/assets/stylesheets/application.scss
This picks up the color variables and does not change the layout as it did when the requires were removed.
=> Add import back in for partials while keeping require statements intact.

app/views/pages/home.html.erb
Please update the link to "Books & Media" button on the main homepage:
Books & Media" link should go to https://librarysearch.temple.edu/catalog, not https://librarysearch.temple.edu/catalog?f[format][]=Book
**********************
Updated link
=> #MAN-478 Update Books & Media link on homepage

Gemfile, Gemfile.lock, app/controllers/forms_controller.rb, app/models/form_submission.rb, config/environments/test.rb, db/migrate/20190725124948_create_form_submissions.rb, db/schema.rb, forms-readme.md, spec/factories/form_submissions.rb, spec/models/form_submission_spec.rb, spec/requests/forms/ask_scrc_spec.rb, spec/requests/forms/missing_book_spec.rb, spec/requests/forms/recall_book_spec.rb, spec/support/form_helper.rb
As form field vary greatly between form, we cannot persist them with a
column for each field. Instead we serialize as JSON the attributes into
`form_attributes`.
Because forms may contain sensitve data, we encrypt the form_attributes
before they are saved to the DB, and are decrypted on access via the
model, assuming  LOCKBOX_MASTER_KEY nev var value is the same it was at
the time of encryption.
This PR also adds some tests to a few forms to ensure the form renders,
can send email (in a test environment), and persists the submitted data
to the db. There are still several forms that require tests.
Blocked by https://github.com/tulibraries/ansible-playbook-manifold/pull/61
=> All forms successfully emailed are persisted

app/assets/stylesheets/finding_aids.scss, app/assets/stylesheets/partials/_footer.scss, app/assets/stylesheets/partials/_mainmenu.scss, app/assets/stylesheets/partials/_searchbar.scss, app/views/application/_header_navbar.html.erb
We want the top navigation to be highlighted when you're on one of those pages-- About, Visit & Study, etc... 
As a result, please make all of the navigation items the same green with the darker color vertical line separating each item. Then, when a user is on the top-level index page (About, Visit & Study, etc), that nav item will be highlighted using the darker green. However, when the user navigates to a sub-index page  from the top-level index page, all nav goes back to regular green. 
Remove all vertical lines in primary navigation.
Added checks for active page and highlighted corresponding menu item.
=> #MAN-389 Modify color of top nav to show page

app/views/finding_aids/_aid_list.html.erb
On  https://web.qa.tul-infra.page/finding_aids, the ending links are conflated (both call and email sends you to the Ask SCRC page).  Update the paragraph to read "..call us at 215-204-8257, or email us." and just have the "email us" linked
Updated link in intro text
=> #MAN-480 Content changes SCRC finding aids

config/application.rb
I added links to https://web.qa.tul-infra.page/admin/pages/18 and set them to open in a new window. But when I click on the link in the live site, it still opens in the same window.
Added allowed attributes to global config.
=> #MAN-415 Links not opening in a new window

app/controllers/library_hours_controller.rb, app/services/sync_service/library_hours.rb
Removed Student Success Center form hours sync and display.
=> #MAN-516 Remove Student Success Center from library hours

app/assets/stylesheets/blogs.scss
Please move the left column blog list to the right to align with the title "Library Blogs"
Aligned title and content in blogs list section.
=> #MAN-567 Alignment issue on Blogs page

app/controllers/admin/redirects_controller.rb, app/controllers/redirects_controller.rb, app/dashboards/redirect_dashboard.rb, app/models/redirect.rb, config/brakeman.ignore, config/locales/en.yml, config/routes.rb, db/migrate/20190806225436_create_redirects_table.rb, db/schema.rb, spec/controllers/redirects_controller_spec.rb, spec/factories/redirects.rb, spec/models/redirect_spec.rb, spec/requests/admin/redirect_spec.rb, spec/requests/redirects_spec.rb
Adds a redirect model that allows administrate users to
- define an incoming legacy_path ("/scrc/ask")
- define either
- a static local path it should go to ("/forms/ask-scrc")
- a redirectable object it should redirect to. Can choose from
- Buildings
- Collections
- Pages
- Spaces
- Services
- Policies
Any non matched redirect reverts to a 404
- Go to the Redirects  admin dashboard  - /admin/redirects
- Create a new redirect
- add a legacy_url i.e ("scrc/ask-here") (should not start with a slash)
- add known static path in the manifold_url ("/forms/ask-scrc") (needs to start with a slash)
- go to localhost:3000/scrc/ask-here - it shoudl redirect to localhost:3000/forms/ask-scrc
- Create a new redirect
- add a legacy_url i.e ("some/place") (should not start with a slash)
- add a …
=> Add a redirect model and dashboard

app/controllers/application_controller.rb, app/views/application/_building_hours.html.erb, app/views/application/_building_mobile_hours.html.erb, app/views/application/_space_hours.html.erb, app/views/application/_space_mobile_hours.html.erb, app/views/library_hours/_desktop.html.erb
Dates needed to be sorted within the seven day range displayed in the views. 
The order becomes random if any updates are made in the spreadsheet to a date within the range.
=> Hours not displaying correct data for dates

app/assets/stylesheets/pages.scss, app/controllers/pages_controller.rb, app/views/pages/_categories.html.erb, app/views/pages/contact.html.erb, app/views/pages/contact/_four.html.erb, app/views/pages/contact/_one.html.erb, app/views/pages/contact/_three.html.erb, app/views/pages/contact/_two.html.erb
The pages associated with the main menu items, showing the categories assigned to that parent category, need to be redone to make the icon links and the text links into one link with and icon and text in it. This is for accessibility.
Remove duplicate links in category views. 
Remove internal links using IDs and change to slugs where possible.
Some instance variables have been set to sue slugs. Slugs needed for this PR are:
-     @fcn_link = Page.find_by_slug("numbers")
-     @libanswers = ExternalLink.find_by_slug("libanswers")
-     @suggestions = Blog.find_by_slug("suggestions").base_url
=> #MAN-574 Refactor page views on main menu items

app/assets/stylesheets/persons.scss
Updated appointment button for mobile view: preventing awkward word wrap by displaying buttons as stacking blocks.
=> #MAN-578 Mobile staff directory - make appointment button not displaying properly

app/assets/stylesheets/buildings.scss, app/views/buildings/show.html.erb, app/views/spaces/show.html.erb
1. Please fix the spacing on the address. If an address takes up two lines, they should be closer together.
2. Is it possible to make the icon top-align with the text next to it instead of middle-aligned?
3. See: https://web.qa.tul-infra.page/libraries/3
4. replace with the same icons you’re using for the space entity
Changed icons. Adjusted spacing.
=> #MAN-583 Fix address alignment in library page

app/models/external_link.rb, spec/factories/external_links.rb, spec/models/external_link_spec.rb
Allow urls paths in the External Links link field, so that we can link to static paths in the manifodl app from nav menu's.
=> Allow urls paths in External Links

app/assets/stylesheets/persons.scss
The downward carrot that indicates a opened facet on events show pages (what else can I call that thing) was way to big in IE, so I've removed the larger font size declaration. Has a minimal effect on other browsers, making it ust a tiny bit smaller.
=> Don't make font awesome charaters larger

app/models/form.rb
Some forms don't include the email and name fields, so the attributes
are not available when sending the email, which causes a syntax error.
=> Add default email and name for forms

app/controllers/pages_controller.rb
The links in this box aren't current workshops.  The only way to see current workshops is to click on "view all".
- This collects the events that end after the current time and shows takes the next 5.
- Change applied to HSL and LCDSS events.
=> MAN-605 Test that the event is now or in the future

app/views/events/index.html.erb, app/views/events/past.html.erb, config/locales/en.yml
MAN-610
After a closer review of the events page, we would like to make the
following updates:
1) Please update the text to say "Most Temple University Libraries events
are free and open to all." We want to clarify that not all are open to all
(especially our workshops and events at other library locations)
2) When I spoke with Cynthia about the page, she mentioned it would be
possible to add brief text at the top of the site to explain our events. We
would like to have the text say "Temple University Libraries offer a
variety of events and workshops throughout the semester under our *Beyond
the Page* series. This series invites scholars, writers, artists, and
experts in a variety of fields to address topics pertinent to scholarship
at Temple and of importance to the university and the …
=> Add Events & Exhibits explanation

app/controllers/scrc_controller.rb, spec/requests/scrc_controller_spec.rb
Finding aid requests of the /scrc/finding-aid-name were no longer working due to changes in the way redirect paths were being handled.
This handles there case.
Also, actually test the scrc controllers now. :(
=> Fix finding aid path redirects.

config/environments/production.rb
Skylight was not getting data because of an error in RSwag api
middleware. This reduces the granularity of skylight reporting for
midleware in order to get data on app performance.
https://www.skylight.io/support/troubleshooting#event-errors
=> Tell skylight not to track  middleware

app/assets/stylesheets/partials/_footer.scss, app/views/application/_footer.html.erb
Chris, IA told us to remove the gift icon from the button, therefore it doesn't need to be an image file anymore.
Can you make a button- same size and rounded corners as the call to action buttons on the services pages?
-Button with rounded corners
-white fill, no outline
-"Support the Libraries" in cherry red, Roboto Condensed font, 24px
-same location in footer
=> #MAN-624 Create new Support the Libraries button for footer

app/models/event.rb
..."here are incorrect times listed for our Thursday Thirty workshops (held
> today, 10/3, 11/7, and 12/5). The start time is 12:15 but the event page
> has 12 pm as the start time. Can this be corrected? It only looks like it's
> an issue on the TUL events pages, like the one seen here:
>
> https://library.temple.edu/events/642
>
> The university events calendar has the correct time."
=> #MAN-637 FWD: correction on calendar

app/helpers/event_helper.rb, app/views/events/_events.html.erb, app/views/events/_facets.html.erb, config/locales/en.yml, spec/helpers/event_helper_spec.rb
Any events that come in from the university event calendar with a location of "Sullivan hall" should be changed to read "Sullivan Hall - Blockson Collection". This is a change to the label that is displayed in Manifold since we cannot change the location that comes through from the university events calendar.
=> #MAN-622 Events change display name for Sullivan Hall

app/controllers/admin/library_hours_controller.rb
Last Library Hours Sync: 09/18/2018 3:38 PM
This is not updating when syncing the hours. It's stuck on the date above.
=> #MAN-347 Fix timestamp on hours sync

app/views/events/index.html.erb
How do I get to the videos? I see a link on the /events page that says “Past events and recordings”, but I don’t see the recordings.
Assuming these were lost in a conflict resolution:
- Enabled video button. 
- Updated link on video button.
=> #MAN-166 List of Videos

app/controllers/application_controller.rb, app/controllers/library_hours_controller.rb, app/services/sync_service/library_hours.rb, app/views/library_hours/_desktop.html.erb, app/views/library_hours/_mobile.html.erb, config/locales/en.yml
But as a start, removing 24/7 as a location and adding a scope note about it at the top of the hours page is a good start.
It could read:
While we list opening and closing times for Charles Library below, the 24/7 space is always available to those affiliated with Temple University. Use your OwlCard to swipe in at the Liacoura and Polett Walks entrance.
=> #MAN-635 Remove 24/7 space from hours

app/assets/stylesheets/collections.scss, app/views/collections/show.html.erb
We added an external link field to the collection entity. However, there is no display for the external link.
Where we would normally have the external link, we currently have an "Explore this collection" button that goes to the finding aid index page. This should stay and we should figure out another way to include the external link.
*************
Added external link button below the Explore button.
=> #MAN-447 Collection entity external link display

app/assets/stylesheets/main.scss, app/assets/stylesheets/partials/_mainmenu.scss
The scrolling alert is currently detached from the main menu and should be attached, with space between it and log-search bar area.
=> #MAN-641 Adjust position of scrolling alert

app/views/pages/about.html.erb, app/views/pages/contact.html.erb, app/views/pages/home.html.erb, app/views/pages/marketing.html.erb, app/views/pages/research.html.erb, app/views/pages/visit.html.erb
Add h1 header with index page name. As of now, there is no indication of where the user has landed in the site when they get to About, Visit & Study, etc.
**********
Added H1 for screen readers, main menu already indicates which page users are on.
=> #MAN-474 Add h1 header with index page name to desktop and mobile

app/assets/stylesheets/finding_aids.scss, app/controllers/finding_aids_controller.rb, app/views/finding_aids/index.html.erb, config/application.rb
On the finding aid index page /finding_aids, please add a CTA button/link to library search that is pre-faceted for finding aids, either from Alma or from manifold. 
**************
Added link to config and called that in the view.
=> #MAN-436 Finding aid index page - link to prefaceted finding aid search

app/controllers/events_controller.rb, app/views/events/past.html.erb
In the /events/past list, when I click on a filter, the events listing starts with 2015. I'm assuming that 2015 is as far back as we go. 
Example: https://web.qa.tul-infra.page/events/past?page=1&type=Performance
I would like to see the most recent past events first. 
************
Also added intro text to past events page.
=> #MAN-492 Past events most recent events first

app/controllers/pages_controller.rb, app/views/pages/contact.html.erb
The "feedback" link on the contact page goes to the What's Your Suggestion blog page.
I think it would be better to make that the link to the form you fill out to submit the feedback - rather than have the customer look for the link on the blog page;
https://sites.temple.edu/librarysuggestions/suggest/
**************
Change instance variable to use external link already setup.
=> #MAN-557 re: give us your feedback

app/controllers/library_hours_controller.rb
https://app.honeybadger.io/projects/58150/faults/41585809#notice-summary
ActionView::Template::Error: undefined method `first' for nil:NilClass
This error was thrown because we don't have hours for this space. We should redirect to a 404 if we don't have that space, not error out like this.
Added the show action back to the controller to handle requests for hours pages (locations) we do not have -- which would be all locations requested since we only have an index for this controller. The previous behavior was to display a blank page with our header and footer and this looked like a mistake.
=> #MAN-243 Cleaner support for MIssing hours

app/controllers/finding_aids_controller.rb, app/helpers/finding_aids_helper.rb, app/views/finding_aids/_subjects.html.erb
Not all the filters selected are displayed in desktop view of finding aids index page. They are all shown in mobile view.
This seems hit or miss as you continue to select more subject filters.
Refactoring the view to use a helper seems to have eliminated the disappearing filter options.
=> #MAN-659 Selected Filters in Finding Aids

app/views/forms/_all.html.erb
When I asked you to add the Partners borrowing request form back to the
website, I should have also asked for you to remove the now unnecessary
forms:
Removed all links from the page that we do not have forms for.
=> #WEB-2916 Patron forms on library website

app/models/person.rb
Increase the number of results per page to 20 instead of 5.
=> #MAN-670 Increase the number of results per page in staff directory

app/views/pages/tudsc.html.erb
Events are not showing on the LCDSS homepage.
****************
Put "Digital Scholarship" into any event's tags and it should show up on the LCDSS homepage under Workshops & Events.
=> #MAN-694 Events on the LCDSS homepage

app/controllers/concerns/person_filters.rb
"....if you select the subject "History," it brings up both Jill and I.
This is incorrect. Jill is liaison to Art History, but I am the only
liaison to History...."
************************
Subject match now set to exact. History only brings up Rebecca.
=> #MAN-601 Staff about page

app/controllers/finding_aids_controller.rb, app/dashboards/collection_dashboard.rb, app/views/finding_aids/show.html.erb, db/migrate/20190926180617_add_slug_field_to_collections.rb, db/schema.rb
Once the new migration is in place, the slug field for the Blockson Collection collection will need the "blockson_collection" identifier added to it.
Then you will not see the Request this item.... link button on any blockson finding aids.
Find blockson aids here: /finding_aids?collection=10
=> #MAN-673 aeon api tweak

app/helpers/event_helper.rb, app/views/events/_events.html.erb, app/views/events/_facets.html.erb, spec/helpers/event_helper_spec.rb
Events without locations (nil building and blank external building) were erroring the view since that nil, or blank, was being passed to the filter helper which populates the filters.
Empty locations are now handled so that they pass through without triggering the filter helpers.
Test this here: https://library.temple.edu/events/past?page=99 (if no error, fix is good)
=> #MAN-675 building name helper function can't take nil as param

Gemfile, Gemfile.lock, spec/features/finding_aids_spec.rb
Issue MAN-674 Add feature tests for Finding Aids
We need to test the finding aids index page, specifically the filters, to ensure that future refactorings do not change expected behavior.
Specific tests include:In the right side filter menu
1) When you select a collecting areaa) it filters to finding aids in that collecting areab) the Subjects available to select are only those from the filtered finding aids
2) when you select a subject filtera) it filters to finding aids with that subjectb) The collecting areas listed are only those from the filtered finding aids
3) When a Collecting Area and a Subject are selecteda) it filters to only finding aids in the collecting area with that subjectb) the remaining Subjects are only those in the filtered findin aids
=> Add finding aid feature specs

config/skylight.yml
As per https://www.skylight.io/support/advanced-setup#ignoring-heartbeathealth-check-endpoints
=> Skylight should ignore OKComputer requests

app/services/sync_service/events.rb
ITS added a new field for external registration links. This work just updates the sync service to check for the new field.
=> #MAN-711 Registration Links Not Pulling To Events Site

app/views/finding_aids/show.html.erb
https://app.honeybadger.io/projects/61882/faults/55590712
Either of these fields being blank is sufficient to not show the link.
=> Finding Aid Error

spec/factories/persons.rb, spec/features/person_spec.rb
MAN-406 Develop more feature tests on Staff Directory
> Using the specialties test as a guide, add more tests to the persons feature test to cover location, department, that only specialists show up when that filter is selected, and that pagination works (two page max).
=> MAN-406 staff specialties feature specs

app/controllers/application_controller.rb, app/views/application/_header-search.html.erb, app/views/application/_mobile-search.html.erb, app/views/pages/home.html.erb
Please update the “Databases” link/button on the homepage to direct to the Springshare A-Z list https://guides.temple.edu/az.php instead of the databases search in library search.
*************
Created external link (in all environments) for the application controller.
Updated home page and header partials to use external link with slug: db-az
=> #MAN-607 Databases link on homepage

config/sitemap.rb
`rake sitemap:create` currently fails with
```
In '/Users/cbn/projects/manifold/public/':
rake aborted!
NameError: undefined local variable or method `library_hours_path' for #<SitemapGenerator::Interpreter:0x00007fae58d2b640>
/Users/cbn/projects/manifold/config/sitemap.rb:44:in `block in run'
/Users/cbn/.rvm/gems/ruby-2.5.1/gems/sitemap_generator-6.0.2/lib/sitemap_generator/interpreter.rb:61:in `instance_eval'
/Users/cbn/.rvm/gems/ruby-2.5.1/gems/sitemap_generator-6.0.2/lib/sitemap_generator/interpreter.rb:61:in `eval'
/Users/cbn/.rvm/gems/ruby-2.5.1/gems/sitemap_generator-6.0.2/lib/sitemap_generator/link_set.rb:40:in `create'
/Users/cbn/.rvm/gems/ruby-2.5.1/gems/sitemap_generator-6.0.2/lib/sitemap_generator.rb:41:in `method_missing'
/Users/cbn/projects/manifold/config/sitemap.rb:6:in …
```
=> Replace non existent hours path helper

app/controllers/buildings_controller.rb, app/controllers/concerns/has_categories.rb, app/controllers/pages_controller.rb, app/controllers/policies_controller.rb, app/controllers/services_controller.rb, app/controllers/spaces_controller.rb, app/dashboards/category_dashboard.rb, app/models/application_record.rb, app/models/categorization.rb, app/models/category.rb, app/views/admin/categories/_form.html.erb, app/views/admin/categories/show.html.erb, app/views/fields/description_field/_show.html.erb, app/views/pages/_items.html.erb, config/database.yml, db/migrate/20191007172619_add_weight_to_categorizations.rb, db/schema.rb, spec/models/category_spec.rb
Items in Categories can now be weighted from 1-10, with 1 being most important, 10 being the least (and the default).
Category Item weightings can be assigned in the Admin Category Edit page.
Weighting will affect order in navigation menus, and order in multiple pages where a categories are used to list the items on a page, like the HSL home page research links, visit links, etc.
This also removes the default alphabetical sort that was in place in those pages.
=> Add weighting to items in categories

app/models/concerns/validators.rb, app/models/finding_aid.rb, spec/factories/finding_aids.rb, spec/models/finding_aid_spec.rb
Can we require that something have either a subject or a collection? That way, they are still browsable in the finding aids index page?
**************
Added custom validation for either/or condition.
=> #MAN-716 website finding aid creation issue

app/controllers/pages_controller.rb, app/views/pages/home.html.erb
On the homepage, please update the link that goes out from "Explore Charles Library" to be https://library.temple.edu/pages/49
**************
"explore-charles" slug added to PAGE: 49 on production; PAGE: 41 on qa (since page 49 does not yet exist on qa).
Marketing page perviously linked still available at: /explore-charles
=> #MAN-721 Change link on "Explore Charles Library" on homepage

app/assets/stylesheets/administrate/components/_main-content.scss, app/controllers/admin/alerts_controller.rb, app/dashboards/alert_dashboard.rb
1. Add a down arrow/up arrow to the header row to indicate that the column can be re-ordered.
2. Add a column for to represent the "Published" checkbox. Results can be represented as "True" and "False"
3. Remove the "Description" field from the list. Keep the field in the model, but hide it from the list display.
******************
Since only one column can be sorted at a time, I’ve sorted by Scroll Text. You’ll see the arrow there indicating it can be sorted. We can’t add arrows to all columns as arrows disappear automatically from non-sorted columns.
=> #MAN-709 Updates to Alert Entity Fields

app/views/events/index.html.erb
The sign up link on /events says "Sign Up for our mailing list" with a
capital U but it should be a lowercase u.
=> #MAN-727 Copy fix on events

app/controllers/pages_controller.rb, app/views/pages/wpvi.html.erb, config/routes.rb
Redoes the Ensemble streaming for WPVI to use the native Ensemble embedded playlist now that it does not have ADA outstanding concerns.
Access will be restricted by IP to three machines in the scrc reading room.
For testing, let me know your IP and I'll set it up temporarily for testing.
=> #MAN-700 Recreate WPVI videos page

app/controllers/admin/events_controller.rb, app/dashboards/event_dashboard.rb, app/services/sync_service/events.rb, db/migrate/20191016125318_add_guid_to_events.rb, db/schema.rb, lib/tasks/events_sync.rake, spec/controllers/admin/events_controller_spec.rb, spec/fixtures/files/badimage-event.xml, spec/fixtures/files/events-onebad.xml, spec/rails_helper.rb, spec/services/sync_events_spec.rb
Adds much more granular logging of event sync jobs.
Adds a force option, which causes all events in the feed to overwrite
existing events, not skipping when a matching hash is found. Useful when
code changes are made to the events sync that would not be picked up
because of the content_hash match.
The sync button in the Events dashboard now uses the force sync, so this
can be used manually after deploys the alter this code.
Testing
-------
You should test that:
- Existing Events without a GUID (you can see it in an admin event show page) that appear in the current feed are re-saved with a GUID when running the sync from the Events dashboard.
- When running a sync, no duplicate events are created.
=> Sync based on guid, add verbose logging, force option for event sync

app/models/category.rb, spec/models/category_spec.rb
This way, equally weighted items will have a predicatable order.
=> Add secondary alpha sort to category items

app/views/application/_footer.html.erb, app/views/application/_header-search.html.erb, app/views/application/_header_navbar.html.erb, app/views/application/_mobile-nav.html.erb, app/views/application/_mobile-search.html.erb, app/views/pages/home.html.erb
Update all instance variable calls (slugs, for example) in templates to check for existence of the variable before trying to render of manipulate it.
=> #MAN-629 Decouple code from data

app/views/application/_header-search.html.erb, app/views/application/_mobile-search.html.erb, app/views/application/_page-search.html.erb
Blacklight Raange Limit adds search_field=dummy_range if dummy_range is
not set in the query.  This seems to be an outdated requirement that I'm
trying to get removed and thus fix issue, but in the mean time we can
fix our issue simply by making sure we set the param searc_field=all
when submitting queries to the catalog.
REF: https://github.com/projectblacklight/blacklight_range_limit/pull/109
REF: BL-1017
=> [BL-1017] Fix dummy_range field bug.

Gemfile, Gemfile.lock, app/dashboards/admin_group_dashboard.rb, app/models/admin_group.rb, app/views/fields/multi_select_field/_form.html.erb, db/migrate/20191022194027_add_json_attributes_to_admin_group.rb, db/schema.rb, spec/models/admin_group_spec.rb
Allows AdminGroups to be indicated as owners of a Entity type
From JIRA
> The following models should have group ownership at the model level. Ideally, the group ownership would be assigned at the list view and apply to all entities within that model. 
Blogs
Buildings
Events
Exhibitions
External Links
Finding Aids
Groups
Highlights
Library Hours
People
Policies
Redirects
=> Add Entity ownership to AdminGroups

app/helpers/application_helper.rb, app/helpers/event_helper.rb, app/models/building.rb, app/models/concerns/imageable.rb, app/models/concerns/schema_dot_orgable.rb, app/models/event.rb, app/views/buildings/show.html.erb, docs/schema_dot_orgable.md, spec/helpers/application_helper_spec.rb, spec/helpers/event_helper_spec.rb, spec/models/building_spec.rb, spec/models/concerns/schema_dot_orgable.rb, spec/models/event_spec.rb, spec/support/imageable_spec.rb, spec/support/schema_dot_orgable.rb
Creates structured data for buildings.
Refactor to create the JSON-LD with a method to create the LD hash in the model and converting that into JSON in an Application Helper. Applied this refactor to Events and Buildings.
=> MAN-738 Add structured data to buildings

app/views/application/_todays_date.html.erb
This is to match hotfix applied to master this morning.
=> Only display date/time widget if system can retrieve date/time

app/views/admin/categories/show.html.erb
- Categories show page overrides default and won't pickup
the show_website button defined in the application/show.html.erb
=> Render show page button on categories show page

spec/features/swagger_spec.rb, swagger/swagger.json
The route changed, but the path defined in swagger had not been updated. This updates the webpages path in swagger and adds some smoke testing to ensure that all paths defined in swagger return valid json.
=> Update pages path to webpages in swagger

app/assets/javascripts/listeners.js
Added js to send click events on digital collections links to google analytics.
=> #MAN-798 Add Analytics tracking to Digital Collections links

spec/factories/buildings.rb
- Categories, when unweighted should show records in alphabetical
order of their name or title. But we have sequentially numbered
names generated by FactoryBot. So the alphabetical order of
"Building 99" and "Building 100" will be reversed because '1'
will come before '9'. For this test, explicitly name the buildings
to prevent this from happening.
=> MAN-855 - Make string ordering test unambiguous

app/models/blog.rb, app/models/building.rb, app/models/category.rb, app/models/collection.rb, app/models/event.rb, app/models/exhibition.rb, app/models/external_link.rb, app/models/finding_aid.rb, app/models/group.rb, app/models/highlight.rb, app/models/person.rb, app/models/policy.rb, app/models/service.rb, app/models/space.rb, app/models/webpage.rb, app/views/admin/application/show.html.erb
Removes the validation for slug so friendly_id gem can generate new one on save. 
Also updates admin/show route for external links (was being set as exernal_links_path(:id) which does not exist.
=> #MAN-864 Can't save External Link because of slug?

app/serializers/concerns/link_serializable.rb, app/serializers/person_serializer.rb, spec/serializers/building_serializer_spec.rb, spec/serializers/event_serializer_spec.rb, spec/serializers/person_serializer_spec.rb
Update link_serializable concern to better handle object params, and account for pluralization of people in controller names.
=> Serialization testing

app/controllers/collections_controller.rb, app/controllers/concerns/has_categories.rb, spec/requests/collections_spec.rb
Restores find_by in Collections controller when friendly_is is not available. 
Updates redirect_or_404 to use method other than url_for to create link.
=> #MAN-875 Redirects are not working

app/controllers/webpages_controller.rb
Bug not affecting normal operation, but if no id is passed to the show function, an error is generated. this redirects user back to main video page with warning that a video must be selected.
https://app.honeybadger.io/projects/61882/faults/62244496
=> Events Video

.circleci/config.yml
Add ci bundler caching to speed up the build process.
Break out the run steps in the test config to make it easier to read in
the CircleCI gui.
Swith to using a small circle container so we use less resource.
=> Tweak the CirclC config

app/dashboards/file_upload_dashboard.rb, app/models/file_upload.rb, db/migrate/20200429194118_adds_slug_field_to_file_uploads.rb, db/schema.rb
Add slug field to file uploads to prevent errors when trying edit on the web due to admin/application_controller not knowing what friendly is when trying to set the instance for this model.
=> File Upload Friendly Find Fix

app/models/exhibition.rb
Addresses Issue #MAN-922
- Remove leftover attribute from itnitial draftable development
which was causing a draft field to appear for non-admin user
=> Exhibition title shouldn't be draftable

spec/features/dashboard/collection_draft_spec.rb
Issue #MAN-930
- Unable to determine why Capybara cannot write to form elements
when seed=22566. Skip spec for now.
=> MAN-930 - Skip failing test

app/views/webpages/scrc.html.erb
Update link to use redirect to category page.
Redirect needs to be created ("/scrc-collections" => "/categories/scrc-collections").
=> #MAN-931 SCRC Collections Heading link

app/controllers/admin/blogs_controller.rb, app/controllers/webpages_controller.rb, app/views/application/_todays_date.html.erb
Translation call for chat widget not properly quoted in yml file.
Also fixed old translation call on individual blog sync flashes.
=> #MAN-933 Hours are not appearing on the homepage

app/views/library_hours/_desktop.html.erb, app/views/library_hours/_mobile.html.erb
Removed text in Charles listing
Commented it out so it can easily be reactivated later with text set in en.yml
=> #MAN-934 Remove text from hours page

app/controllers/alerts_controller.rb, app/controllers/concerns/serializable_respond_to.rb, app/schemas/alert_schema.json, app/serializers/alert_serializer.rb, config/routes.rb, spec/factories/alerts.rb, spec/serializers/alert_serializer_spec.rb
First part of coupling the library search alerts to the manifold web site alerts.
Provides endpoint at "/alerts.json" to provide alerts that are currently published.
=> #BL-1242 Update banner integration and styling

app/controllers/admin/external_links_controller.rb, app/models/external_link.rb
Remove restrictions in model in favor of overridden destroy method in admin controller. 
They were clashing and we were not getting the custom message.
=> #MAN-948 Error occurred when attempting to delete external link

app/controllers/events_controller.rb, app/views/events/_featured.html.erb
Featured events display now uses the new tag set.
Updated new tags in controller to match on titleize (called from view).
=> #MAN-984 Library Events Page, Wrong Field

app/models/building.rb, app/models/category.rb, app/models/collection.rb, app/models/finding_aid.rb, app/models/group.rb, app/models/person.rb, app/models/space.rb, app/views/fields/has_many/_index.html.erb
Policies with no categories were throwing error on admin index page, checking label on nil entries threw the error.
This fix addresses any model with a has_many relationship.
Also added label method to models without it.
=> Uncategorized Policies

app/assets/javascripts/administrate/admin_redirect.js, app/assets/javascripts/administrate/application.js, app/helpers/application_helper.rb, app/views/admin/application/edit.html.erb, app/views/application/_footer.html.erb, app/views/layouts/administrate/application.html.erb
- Adjusts the login link in the footer to go to that page's admin page rather than a generic admin landing page.
- Admin page redirects to itself on load to get around a browser based issue where admin pages load scrolled to same position that link was located on in previous page: see note below.
Note on JS redirect: 
- If the login link is added to the header, the admin pages open normally (scrolled to top). 
- If the login link is added to the middle of the page, the admin page opens scrolled down to the middle. 
- If the login link is added to the bottom of the page, the admin page opens scrolled down to the bottom. 
- This appears to be an issue of the rails app loading the admin section but the browser not recognizing the change and thus keeping the scrolled location just as if the …
=> #MAN-1003 When logging into the backend take user to page

app/models/finding_aid.rb
Require name field, check subjects exist before weeding nils.
https://app.honeybadger.io/projects/61882/faults/69745145
=> #MAN-1005_Validations Missing on Finding Aid Creation

app/controllers/events_controller.rb, app/views/admin/application/edit.html.erb, app/views/admin/application/show.html.erb, app/views/events/index.html.erb, app/views/events/past.html.erb, app/views/exhibitions/show.html.erb, app/views/fields/date_time/_form.html.erb, config/locales/en.yml, db/schema.rb
Update past events page to show past exhibits. 
Remove titles from show and edit buttons. 
Add back link to exhibit show page.
=> #MAN-1042 link past exhibits to Past programs and Exhibits page

app/services/sync_service/blogs.rb, app/services/sync_service/events.rb
- In Nokogiri, replace open with URI.open
=> Replace deprecated open method

app/services/sync_service/blogs.rb, app/services/sync_service/events.rb
- Suspect that QA and Prod attempt to resolve sites.temple.edu over IPV6, which we have seen timeout
- resolv-replace gem fixes Net::OpenTimeout: execution expired problem, providing an alternative means to resolve Domain Names.
=> DEVO-388 Use resolv-replace to handle timeout on QA and Prod

app/serializers/concerns/long_description_serializable.rb
Models already available.
Removed to_html method on long_description causing error on categories output.
=> #MAN-1098 Add models to web content JSON export

Gemfile, Gemfile.lock
- Skylight version 5 does not work with centos 7. We need to remain pinned at 4.3.2 to have it working
=> DEVO-392 Pin Skylight

Gemfile, Gemfile.lock
It is very important that we pin Skylight to this version and not merge the dependabot updates to bump it.  Version 5 of Skylight is not compatible with Centos7, so we are not getting any data when using it. We haven't had any data for months in this application as a result.  I have pinned this before, but it keeps getting updated before deployment, so the change never gets to production.
=> DEVO-392 Pin Skylight to 4.3.2

.circleci/config.yml
Fixes:
```
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```
=> InRelease' changed its 'Suite' value from 'stable' to 'oldstable

Gemfile, Gemfile.lock, app/models/finding_aid.rb, spec/models/finding_aid_spec.rb, spec/rails_helper.rb
Adds should-matchers gem from Thoughbot to breeze through rspec validations.
Description fields were deleted on several finding aids on staging which caused additional errors in the JSON feed.
=> MAN-1179 Require description in Finding Aids

package.json, yarn.lock
- Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS0
=> MAN-1187 Bump terser from 4.8.0 to 4.8.1

app/models/form.rb
Reply messages were being sent to templelibraries@gmail.com as well as the other recipients. Removing that address from the form header (inadvertently included in the first place) should prevent that in future.
=> Forms Sender Fix

.circleci/config.yml
The other key isn't working to check out the code from the playbook.  In reading documentation, it seems like that is what the user key is for.
=> Try adding user key

.gitlab-ci.yml, Makefile
The previous gitlab file followed old procedures that are no longer used.  This updates us to use the new flow once the charts are ready.
The trivy scans were hanging locally.  This also adds a flag to the privy command to make it run a little faster.
=> DEVO-856 Update gitlab file

.circleci/config.yml, README.md, app/schemas/alert_schema.json, app/schemas/blog_schema.json, app/schemas/building_schema.json, app/schemas/category_schema.json, app/schemas/collection_schema.json, app/schemas/event_schema.json, app/schemas/exhibition_schema.json, app/schemas/finding_aid_schema.json, app/schemas/group_schema.json, app/schemas/highlight_schema.json, app/schemas/person_schema.json, app/schemas/policy_schema.json, app/schemas/service_schema.json, app/schemas/space_schema.json, app/schemas/webpage_schema.json, spec/support/serializable_spec.rb, spec/support/serializer_spec.rb
- Remove ajv from project
- Incorporate JSON::Validator.validate into specs
- Downgrade custom schemas to JSON schema Draft-06 because Ruby json-schema gem does not support Draft-07 or later.
=> MAN-1325 replace ajv with ruby json-schema gem's validate method

Gemfile, Gemfile.lock
I was trying to avoid this, but nothing else seems to work.  The linode QA instance fails with this message:
The application encountered the following error: You have already activated base64 0.1.1, but your Gemfile requires base64 0.2.0. Since base64 is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports base64 as a default gem. (Gem::LoadError)
I tried a newer version of bundler, but that didn't fix the problem.  For now, pinning the gem is the easiest solution.
=> Pin base64 in Gemfile

config/sitemap.rb, public/robots.txt
Engines are listing some pages, but they are also including the following message as the description: "We would like to show you a description here but the site won’t allow us." This work resets the robots directives to pre-restrictive levels, and restrictions can be added on an engine by engine basis.
=> Man-1381 google not harvesting staff profile pages

config/routes.rb, spec/requests/link_exchange_spec.rb
This adds the shortened urls generated through the Link Exchanger.
=> DEVO-1099 Add shortened links for Link Exchanger redirect

app/controllers/admin/application_controller.rb, app/controllers/admin/redirects_controller.rb, spec/system/admin/admin_redirects_spec.rb
- Fixes inability to create redirects
- 1resource_params1 already provided by administrate's application controller which does not have problems with missing primary_key when creating a redirect
- Create spec test for this issue
=> BL-1410 Use Administrate application_controller's resource_params method to fix redirects

config/routes.rb
- Redirects manifold finding-aids index page to Archives Space page
- Requires removal of trailing slash in "Path from Drupal" field.
=> MAN-1410 Redirect finding_aids index page to archives_space

app/controllers/library_hours_controller.rb, app/controllers/webpages_controller.rb, app/services/google/sheets_connector.rb, app/views/application/_todays_date.html.erb, spec/controllers/webpages_controller_spec.rb, spec/fixtures/vcr_cassettes/google_api_error.yml
Addresses issue of homepage not rendering if todays_hours widget gets an error response from google api.
Adds rescues to service object and controller to allow flow of render to proceed without google data
Does not display widget if errors from google
=> Google api errors

app/controllers/admin/events_controller.rb, app/services/sync_service/events.rb, spec/fixtures/files/badimage-event.xml, spec/fixtures/files/noimage-event.xml, spec/fixtures/files/updated_single_event.xml, spec/services/sync_events_spec.rb
The major portion of this solution is that an event that receives the forbidden error message for an image from the university server will now still update the event. This was not how the code was previously setup. There is some refactoring of the sync code to enable this.
Any image error will now be temporarily recorded to cache and the associated event title will be displayed to the user initializing the manual sync for further review. Automatic syncs are no longer enabled, from previous work.
=> MAN-1373 Trap when image fails to attach to event

app/views/fields/string/_form.html.erb
There appears to be manual manipulation of GUID field values, causing duplicate events to be created. This disables the GUID field so there is no user control over it.
=> MAN-1478 Duplicate Event Listings

.github/workflows/lint-test.yml, Gemfile, Gemfile.lock
We cannot put a ruby version in the Gemfile.  The ruby version that we use comes from the base docker image.  If a version is put in the Gemfile, it would have to be updated every time the base image is changed because it breaks the build if the two versions are not the same.  It is cleaner to just let the ruby version come from the base image.
=> No ruby version in Gemfile

.docker/app/Dockerfile
Dockerfile now runs db:seed. 
Only conditional seeds should be used, i.e., unless ModelName.exists?(slug: slug-name)
See current seed file for example. This will make it easier to deploy new/updated features that require a model instance to get started.
=> DB Seed per deploy
